//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace Client_WinPhone.FeedService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebResult", Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client_WinPhone.FeedService.WebResultOfArrayOfChannelMeg_PnYqa))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client_WinPhone.FeedService.WebResultOfArrayOfItemMeg_PnYqa))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client_WinPhone.FeedService.WebResultOfChannelMeg_PnYqa))]
    public partial class WebResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Client_WinPhone.FeedService.WebResult.ErrorCodeList ErrorCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_WinPhone.FeedService.WebResult.ErrorCodeList ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="WebResult.ErrorCodeList", Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
        public enum ErrorCodeList : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SUCCESS = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            USER_NOT_FOUND = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            USER_ALREADY_EXIST = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            INFORMATION_REQUIRED = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NOT_LOGUED = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            INTERNAL_ERROR = 5,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NEED_PRIVILEGE = 6,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ALREADY_LOGUED = 7,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CANNOT_CREATE_FEED = 8,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CANNOT_GET_FEED = 9,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ITEM_NOT_FOUND = 10,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PARAMETER_ERROR = 11,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            INVALID_PARAMETER = 12,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebResultOfArrayOfChannelMeg_PnYqa", Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
    public partial class WebResultOfArrayOfChannelMeg_PnYqa : Client_WinPhone.FeedService.WebResult {
        
        private System.Collections.ObjectModel.ObservableCollection<Client_WinPhone.FeedService.Channel> ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Client_WinPhone.FeedService.Channel> Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebResultOfArrayOfItemMeg_PnYqa", Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
    public partial class WebResultOfArrayOfItemMeg_PnYqa : Client_WinPhone.FeedService.WebResult {
        
        private System.Collections.ObjectModel.ObservableCollection<Client_WinPhone.FeedService.Item> ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Client_WinPhone.FeedService.Item> Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebResultOfChannelMeg_PnYqa", Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
    public partial class WebResultOfChannelMeg_PnYqa : Client_WinPhone.FeedService.WebResult {
        
        private Client_WinPhone.FeedService.Channel ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_WinPhone.FeedService.Channel Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Channel", Namespace="http://schemas.datacontract.org/2004/07/Server.Data")]
    public partial class Channel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DescriptionField;
        
        private string EnclosureField;
        
        private int IdField;
        
        private string ImageField;
        
        private System.Nullable<System.DateTime> LastBuildDateField;
        
        private string LinkField;
        
        private System.Nullable<System.DateTime> PubDateField;
        
        private string TitleField;
        
        private string UrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Enclosure {
            get {
                return this.EnclosureField;
            }
            set {
                if ((object.ReferenceEquals(this.EnclosureField, value) != true)) {
                    this.EnclosureField = value;
                    this.RaisePropertyChanged("Enclosure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastBuildDate {
            get {
                return this.LastBuildDateField;
            }
            set {
                if ((this.LastBuildDateField.Equals(value) != true)) {
                    this.LastBuildDateField = value;
                    this.RaisePropertyChanged("LastBuildDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PubDate {
            get {
                return this.PubDateField;
            }
            set {
                if ((this.PubDateField.Equals(value) != true)) {
                    this.PubDateField = value;
                    this.RaisePropertyChanged("PubDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/Server.Data")]
    public partial class Item : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AuthorField;
        
        private string CategoryField;
        
        private string CommentsField;
        
        private string DescriptionField;
        
        private string GUIDField;
        
        private int IdField;
        
        private int IdChannelField;
        
        private string LinkField;
        
        private System.Nullable<System.DateTimeOffset> PubDateField;
        
        private bool ReadField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GUID {
            get {
                return this.GUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.GUIDField, value) != true)) {
                    this.GUIDField = value;
                    this.RaisePropertyChanged("GUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdChannel {
            get {
                return this.IdChannelField;
            }
            set {
                if ((this.IdChannelField.Equals(value) != true)) {
                    this.IdChannelField = value;
                    this.RaisePropertyChanged("IdChannel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTimeOffset> PubDate {
            get {
                return this.PubDateField;
            }
            set {
                if ((this.PubDateField.Equals(value) != true)) {
                    this.PubDateField = value;
                    this.RaisePropertyChanged("PubDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Read {
            get {
                return this.ReadField;
            }
            set {
                if ((this.ReadField.Equals(value) != true)) {
                    this.ReadField = value;
                    this.RaisePropertyChanged("Read");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FeedService.FeedsService")]
    public interface FeedsService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/FeedsService/AddNewFeed", ReplyAction="http://tempuri.org/FeedsService/AddNewFeedResponse")]
        System.IAsyncResult BeginAddNewFeed(string connectionKey, System.Uri uri, System.AsyncCallback callback, object asyncState);
        
        Client_WinPhone.FeedService.WebResultOfChannelMeg_PnYqa EndAddNewFeed(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/FeedsService/GetFeeds", ReplyAction="http://tempuri.org/FeedsService/GetFeedsResponse")]
        System.IAsyncResult BeginGetFeeds(string connectionKey, System.AsyncCallback callback, object asyncState);
        
        Client_WinPhone.FeedService.WebResultOfArrayOfChannelMeg_PnYqa EndGetFeeds(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/FeedsService/GetAllFeeds", ReplyAction="http://tempuri.org/FeedsService/GetAllFeedsResponse")]
        System.IAsyncResult BeginGetAllFeeds(System.AsyncCallback callback, object asyncState);
        
        Client_WinPhone.FeedService.WebResultOfArrayOfChannelMeg_PnYqa EndGetAllFeeds(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/FeedsService/UnfollowFeed", ReplyAction="http://tempuri.org/FeedsService/UnfollowFeedResponse")]
        System.IAsyncResult BeginUnfollowFeed(string connectionKey, Client_WinPhone.FeedService.Channel feed, System.AsyncCallback callback, object asyncState);
        
        Client_WinPhone.FeedService.WebResult EndUnfollowFeed(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/FeedsService/GetFeedItems", ReplyAction="http://tempuri.org/FeedsService/GetFeedItemsResponse")]
        System.IAsyncResult BeginGetFeedItems(string connectionKey, Client_WinPhone.FeedService.Channel feed, System.AsyncCallback callback, object asyncState);
        
        Client_WinPhone.FeedService.WebResultOfArrayOfItemMeg_PnYqa EndGetFeedItems(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/FeedsService/ReadItem", ReplyAction="http://tempuri.org/FeedsService/ReadItemResponse")]
        System.IAsyncResult BeginReadItem(string connectionKey, Client_WinPhone.FeedService.Item item, System.AsyncCallback callback, object asyncState);
        
        Client_WinPhone.FeedService.WebResult EndReadItem(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/FeedsService/RefreshFeed", ReplyAction="http://tempuri.org/FeedsService/RefreshFeedResponse")]
        System.IAsyncResult BeginRefreshFeed(Client_WinPhone.FeedService.Channel feed, System.AsyncCallback callback, object asyncState);
        
        Client_WinPhone.FeedService.WebResult EndRefreshFeed(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FeedsServiceChannel : Client_WinPhone.FeedService.FeedsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddNewFeedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddNewFeedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WinPhone.FeedService.WebResultOfChannelMeg_PnYqa Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WinPhone.FeedService.WebResultOfChannelMeg_PnYqa)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFeedsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFeedsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WinPhone.FeedService.WebResultOfArrayOfChannelMeg_PnYqa Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WinPhone.FeedService.WebResultOfArrayOfChannelMeg_PnYqa)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllFeedsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllFeedsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WinPhone.FeedService.WebResultOfArrayOfChannelMeg_PnYqa Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WinPhone.FeedService.WebResultOfArrayOfChannelMeg_PnYqa)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UnfollowFeedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UnfollowFeedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WinPhone.FeedService.WebResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WinPhone.FeedService.WebResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFeedItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFeedItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WinPhone.FeedService.WebResultOfArrayOfItemMeg_PnYqa Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WinPhone.FeedService.WebResultOfArrayOfItemMeg_PnYqa)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReadItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ReadItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WinPhone.FeedService.WebResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WinPhone.FeedService.WebResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RefreshFeedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RefreshFeedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WinPhone.FeedService.WebResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WinPhone.FeedService.WebResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FeedsServiceClient : System.ServiceModel.ClientBase<Client_WinPhone.FeedService.FeedsService>, Client_WinPhone.FeedService.FeedsService {
        
        private BeginOperationDelegate onBeginAddNewFeedDelegate;
        
        private EndOperationDelegate onEndAddNewFeedDelegate;
        
        private System.Threading.SendOrPostCallback onAddNewFeedCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetFeedsDelegate;
        
        private EndOperationDelegate onEndGetFeedsDelegate;
        
        private System.Threading.SendOrPostCallback onGetFeedsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllFeedsDelegate;
        
        private EndOperationDelegate onEndGetAllFeedsDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllFeedsCompletedDelegate;
        
        private BeginOperationDelegate onBeginUnfollowFeedDelegate;
        
        private EndOperationDelegate onEndUnfollowFeedDelegate;
        
        private System.Threading.SendOrPostCallback onUnfollowFeedCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetFeedItemsDelegate;
        
        private EndOperationDelegate onEndGetFeedItemsDelegate;
        
        private System.Threading.SendOrPostCallback onGetFeedItemsCompletedDelegate;
        
        private BeginOperationDelegate onBeginReadItemDelegate;
        
        private EndOperationDelegate onEndReadItemDelegate;
        
        private System.Threading.SendOrPostCallback onReadItemCompletedDelegate;
        
        private BeginOperationDelegate onBeginRefreshFeedDelegate;
        
        private EndOperationDelegate onEndRefreshFeedDelegate;
        
        private System.Threading.SendOrPostCallback onRefreshFeedCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public FeedsServiceClient() {
        }
        
        public FeedsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FeedsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeedsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeedsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<AddNewFeedCompletedEventArgs> AddNewFeedCompleted;
        
        public event System.EventHandler<GetFeedsCompletedEventArgs> GetFeedsCompleted;
        
        public event System.EventHandler<GetAllFeedsCompletedEventArgs> GetAllFeedsCompleted;
        
        public event System.EventHandler<UnfollowFeedCompletedEventArgs> UnfollowFeedCompleted;
        
        public event System.EventHandler<GetFeedItemsCompletedEventArgs> GetFeedItemsCompleted;
        
        public event System.EventHandler<ReadItemCompletedEventArgs> ReadItemCompleted;
        
        public event System.EventHandler<RefreshFeedCompletedEventArgs> RefreshFeedCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Client_WinPhone.FeedService.FeedsService.BeginAddNewFeed(string connectionKey, System.Uri uri, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddNewFeed(connectionKey, uri, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WinPhone.FeedService.WebResultOfChannelMeg_PnYqa Client_WinPhone.FeedService.FeedsService.EndAddNewFeed(System.IAsyncResult result) {
            return base.Channel.EndAddNewFeed(result);
        }
        
        private System.IAsyncResult OnBeginAddNewFeed(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string connectionKey = ((string)(inValues[0]));
            System.Uri uri = ((System.Uri)(inValues[1]));
            return ((Client_WinPhone.FeedService.FeedsService)(this)).BeginAddNewFeed(connectionKey, uri, callback, asyncState);
        }
        
        private object[] OnEndAddNewFeed(System.IAsyncResult result) {
            Client_WinPhone.FeedService.WebResultOfChannelMeg_PnYqa retVal = ((Client_WinPhone.FeedService.FeedsService)(this)).EndAddNewFeed(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddNewFeedCompleted(object state) {
            if ((this.AddNewFeedCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddNewFeedCompleted(this, new AddNewFeedCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddNewFeedAsync(string connectionKey, System.Uri uri) {
            this.AddNewFeedAsync(connectionKey, uri, null);
        }
        
        public void AddNewFeedAsync(string connectionKey, System.Uri uri, object userState) {
            if ((this.onBeginAddNewFeedDelegate == null)) {
                this.onBeginAddNewFeedDelegate = new BeginOperationDelegate(this.OnBeginAddNewFeed);
            }
            if ((this.onEndAddNewFeedDelegate == null)) {
                this.onEndAddNewFeedDelegate = new EndOperationDelegate(this.OnEndAddNewFeed);
            }
            if ((this.onAddNewFeedCompletedDelegate == null)) {
                this.onAddNewFeedCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddNewFeedCompleted);
            }
            base.InvokeAsync(this.onBeginAddNewFeedDelegate, new object[] {
                        connectionKey,
                        uri}, this.onEndAddNewFeedDelegate, this.onAddNewFeedCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Client_WinPhone.FeedService.FeedsService.BeginGetFeeds(string connectionKey, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFeeds(connectionKey, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WinPhone.FeedService.WebResultOfArrayOfChannelMeg_PnYqa Client_WinPhone.FeedService.FeedsService.EndGetFeeds(System.IAsyncResult result) {
            return base.Channel.EndGetFeeds(result);
        }
        
        private System.IAsyncResult OnBeginGetFeeds(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string connectionKey = ((string)(inValues[0]));
            return ((Client_WinPhone.FeedService.FeedsService)(this)).BeginGetFeeds(connectionKey, callback, asyncState);
        }
        
        private object[] OnEndGetFeeds(System.IAsyncResult result) {
            Client_WinPhone.FeedService.WebResultOfArrayOfChannelMeg_PnYqa retVal = ((Client_WinPhone.FeedService.FeedsService)(this)).EndGetFeeds(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFeedsCompleted(object state) {
            if ((this.GetFeedsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFeedsCompleted(this, new GetFeedsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFeedsAsync(string connectionKey) {
            this.GetFeedsAsync(connectionKey, null);
        }
        
        public void GetFeedsAsync(string connectionKey, object userState) {
            if ((this.onBeginGetFeedsDelegate == null)) {
                this.onBeginGetFeedsDelegate = new BeginOperationDelegate(this.OnBeginGetFeeds);
            }
            if ((this.onEndGetFeedsDelegate == null)) {
                this.onEndGetFeedsDelegate = new EndOperationDelegate(this.OnEndGetFeeds);
            }
            if ((this.onGetFeedsCompletedDelegate == null)) {
                this.onGetFeedsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFeedsCompleted);
            }
            base.InvokeAsync(this.onBeginGetFeedsDelegate, new object[] {
                        connectionKey}, this.onEndGetFeedsDelegate, this.onGetFeedsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Client_WinPhone.FeedService.FeedsService.BeginGetAllFeeds(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllFeeds(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WinPhone.FeedService.WebResultOfArrayOfChannelMeg_PnYqa Client_WinPhone.FeedService.FeedsService.EndGetAllFeeds(System.IAsyncResult result) {
            return base.Channel.EndGetAllFeeds(result);
        }
        
        private System.IAsyncResult OnBeginGetAllFeeds(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Client_WinPhone.FeedService.FeedsService)(this)).BeginGetAllFeeds(callback, asyncState);
        }
        
        private object[] OnEndGetAllFeeds(System.IAsyncResult result) {
            Client_WinPhone.FeedService.WebResultOfArrayOfChannelMeg_PnYqa retVal = ((Client_WinPhone.FeedService.FeedsService)(this)).EndGetAllFeeds(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllFeedsCompleted(object state) {
            if ((this.GetAllFeedsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllFeedsCompleted(this, new GetAllFeedsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllFeedsAsync() {
            this.GetAllFeedsAsync(null);
        }
        
        public void GetAllFeedsAsync(object userState) {
            if ((this.onBeginGetAllFeedsDelegate == null)) {
                this.onBeginGetAllFeedsDelegate = new BeginOperationDelegate(this.OnBeginGetAllFeeds);
            }
            if ((this.onEndGetAllFeedsDelegate == null)) {
                this.onEndGetAllFeedsDelegate = new EndOperationDelegate(this.OnEndGetAllFeeds);
            }
            if ((this.onGetAllFeedsCompletedDelegate == null)) {
                this.onGetAllFeedsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllFeedsCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllFeedsDelegate, null, this.onEndGetAllFeedsDelegate, this.onGetAllFeedsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Client_WinPhone.FeedService.FeedsService.BeginUnfollowFeed(string connectionKey, Client_WinPhone.FeedService.Channel feed, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUnfollowFeed(connectionKey, feed, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WinPhone.FeedService.WebResult Client_WinPhone.FeedService.FeedsService.EndUnfollowFeed(System.IAsyncResult result) {
            return base.Channel.EndUnfollowFeed(result);
        }
        
        private System.IAsyncResult OnBeginUnfollowFeed(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string connectionKey = ((string)(inValues[0]));
            Client_WinPhone.FeedService.Channel feed = ((Client_WinPhone.FeedService.Channel)(inValues[1]));
            return ((Client_WinPhone.FeedService.FeedsService)(this)).BeginUnfollowFeed(connectionKey, feed, callback, asyncState);
        }
        
        private object[] OnEndUnfollowFeed(System.IAsyncResult result) {
            Client_WinPhone.FeedService.WebResult retVal = ((Client_WinPhone.FeedService.FeedsService)(this)).EndUnfollowFeed(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUnfollowFeedCompleted(object state) {
            if ((this.UnfollowFeedCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UnfollowFeedCompleted(this, new UnfollowFeedCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UnfollowFeedAsync(string connectionKey, Client_WinPhone.FeedService.Channel feed) {
            this.UnfollowFeedAsync(connectionKey, feed, null);
        }
        
        public void UnfollowFeedAsync(string connectionKey, Client_WinPhone.FeedService.Channel feed, object userState) {
            if ((this.onBeginUnfollowFeedDelegate == null)) {
                this.onBeginUnfollowFeedDelegate = new BeginOperationDelegate(this.OnBeginUnfollowFeed);
            }
            if ((this.onEndUnfollowFeedDelegate == null)) {
                this.onEndUnfollowFeedDelegate = new EndOperationDelegate(this.OnEndUnfollowFeed);
            }
            if ((this.onUnfollowFeedCompletedDelegate == null)) {
                this.onUnfollowFeedCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUnfollowFeedCompleted);
            }
            base.InvokeAsync(this.onBeginUnfollowFeedDelegate, new object[] {
                        connectionKey,
                        feed}, this.onEndUnfollowFeedDelegate, this.onUnfollowFeedCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Client_WinPhone.FeedService.FeedsService.BeginGetFeedItems(string connectionKey, Client_WinPhone.FeedService.Channel feed, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFeedItems(connectionKey, feed, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WinPhone.FeedService.WebResultOfArrayOfItemMeg_PnYqa Client_WinPhone.FeedService.FeedsService.EndGetFeedItems(System.IAsyncResult result) {
            return base.Channel.EndGetFeedItems(result);
        }
        
        private System.IAsyncResult OnBeginGetFeedItems(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string connectionKey = ((string)(inValues[0]));
            Client_WinPhone.FeedService.Channel feed = ((Client_WinPhone.FeedService.Channel)(inValues[1]));
            return ((Client_WinPhone.FeedService.FeedsService)(this)).BeginGetFeedItems(connectionKey, feed, callback, asyncState);
        }
        
        private object[] OnEndGetFeedItems(System.IAsyncResult result) {
            Client_WinPhone.FeedService.WebResultOfArrayOfItemMeg_PnYqa retVal = ((Client_WinPhone.FeedService.FeedsService)(this)).EndGetFeedItems(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFeedItemsCompleted(object state) {
            if ((this.GetFeedItemsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFeedItemsCompleted(this, new GetFeedItemsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFeedItemsAsync(string connectionKey, Client_WinPhone.FeedService.Channel feed) {
            this.GetFeedItemsAsync(connectionKey, feed, null);
        }
        
        public void GetFeedItemsAsync(string connectionKey, Client_WinPhone.FeedService.Channel feed, object userState) {
            if ((this.onBeginGetFeedItemsDelegate == null)) {
                this.onBeginGetFeedItemsDelegate = new BeginOperationDelegate(this.OnBeginGetFeedItems);
            }
            if ((this.onEndGetFeedItemsDelegate == null)) {
                this.onEndGetFeedItemsDelegate = new EndOperationDelegate(this.OnEndGetFeedItems);
            }
            if ((this.onGetFeedItemsCompletedDelegate == null)) {
                this.onGetFeedItemsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFeedItemsCompleted);
            }
            base.InvokeAsync(this.onBeginGetFeedItemsDelegate, new object[] {
                        connectionKey,
                        feed}, this.onEndGetFeedItemsDelegate, this.onGetFeedItemsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Client_WinPhone.FeedService.FeedsService.BeginReadItem(string connectionKey, Client_WinPhone.FeedService.Item item, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReadItem(connectionKey, item, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WinPhone.FeedService.WebResult Client_WinPhone.FeedService.FeedsService.EndReadItem(System.IAsyncResult result) {
            return base.Channel.EndReadItem(result);
        }
        
        private System.IAsyncResult OnBeginReadItem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string connectionKey = ((string)(inValues[0]));
            Client_WinPhone.FeedService.Item item = ((Client_WinPhone.FeedService.Item)(inValues[1]));
            return ((Client_WinPhone.FeedService.FeedsService)(this)).BeginReadItem(connectionKey, item, callback, asyncState);
        }
        
        private object[] OnEndReadItem(System.IAsyncResult result) {
            Client_WinPhone.FeedService.WebResult retVal = ((Client_WinPhone.FeedService.FeedsService)(this)).EndReadItem(result);
            return new object[] {
                    retVal};
        }
        
        private void OnReadItemCompleted(object state) {
            if ((this.ReadItemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReadItemCompleted(this, new ReadItemCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReadItemAsync(string connectionKey, Client_WinPhone.FeedService.Item item) {
            this.ReadItemAsync(connectionKey, item, null);
        }
        
        public void ReadItemAsync(string connectionKey, Client_WinPhone.FeedService.Item item, object userState) {
            if ((this.onBeginReadItemDelegate == null)) {
                this.onBeginReadItemDelegate = new BeginOperationDelegate(this.OnBeginReadItem);
            }
            if ((this.onEndReadItemDelegate == null)) {
                this.onEndReadItemDelegate = new EndOperationDelegate(this.OnEndReadItem);
            }
            if ((this.onReadItemCompletedDelegate == null)) {
                this.onReadItemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReadItemCompleted);
            }
            base.InvokeAsync(this.onBeginReadItemDelegate, new object[] {
                        connectionKey,
                        item}, this.onEndReadItemDelegate, this.onReadItemCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Client_WinPhone.FeedService.FeedsService.BeginRefreshFeed(Client_WinPhone.FeedService.Channel feed, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRefreshFeed(feed, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WinPhone.FeedService.WebResult Client_WinPhone.FeedService.FeedsService.EndRefreshFeed(System.IAsyncResult result) {
            return base.Channel.EndRefreshFeed(result);
        }
        
        private System.IAsyncResult OnBeginRefreshFeed(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Client_WinPhone.FeedService.Channel feed = ((Client_WinPhone.FeedService.Channel)(inValues[0]));
            return ((Client_WinPhone.FeedService.FeedsService)(this)).BeginRefreshFeed(feed, callback, asyncState);
        }
        
        private object[] OnEndRefreshFeed(System.IAsyncResult result) {
            Client_WinPhone.FeedService.WebResult retVal = ((Client_WinPhone.FeedService.FeedsService)(this)).EndRefreshFeed(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRefreshFeedCompleted(object state) {
            if ((this.RefreshFeedCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RefreshFeedCompleted(this, new RefreshFeedCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RefreshFeedAsync(Client_WinPhone.FeedService.Channel feed) {
            this.RefreshFeedAsync(feed, null);
        }
        
        public void RefreshFeedAsync(Client_WinPhone.FeedService.Channel feed, object userState) {
            if ((this.onBeginRefreshFeedDelegate == null)) {
                this.onBeginRefreshFeedDelegate = new BeginOperationDelegate(this.OnBeginRefreshFeed);
            }
            if ((this.onEndRefreshFeedDelegate == null)) {
                this.onEndRefreshFeedDelegate = new EndOperationDelegate(this.OnEndRefreshFeed);
            }
            if ((this.onRefreshFeedCompletedDelegate == null)) {
                this.onRefreshFeedCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRefreshFeedCompleted);
            }
            base.InvokeAsync(this.onBeginRefreshFeedDelegate, new object[] {
                        feed}, this.onEndRefreshFeedDelegate, this.onRefreshFeedCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Client_WinPhone.FeedService.FeedsService CreateChannel() {
            return new FeedsServiceClientChannel(this);
        }
        
        private class FeedsServiceClientChannel : ChannelBase<Client_WinPhone.FeedService.FeedsService>, Client_WinPhone.FeedService.FeedsService {
            
            public FeedsServiceClientChannel(System.ServiceModel.ClientBase<Client_WinPhone.FeedService.FeedsService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginAddNewFeed(string connectionKey, System.Uri uri, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = connectionKey;
                _args[1] = uri;
                System.IAsyncResult _result = base.BeginInvoke("AddNewFeed", _args, callback, asyncState);
                return _result;
            }
            
            public Client_WinPhone.FeedService.WebResultOfChannelMeg_PnYqa EndAddNewFeed(System.IAsyncResult result) {
                object[] _args = new object[0];
                Client_WinPhone.FeedService.WebResultOfChannelMeg_PnYqa _result = ((Client_WinPhone.FeedService.WebResultOfChannelMeg_PnYqa)(base.EndInvoke("AddNewFeed", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetFeeds(string connectionKey, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = connectionKey;
                System.IAsyncResult _result = base.BeginInvoke("GetFeeds", _args, callback, asyncState);
                return _result;
            }
            
            public Client_WinPhone.FeedService.WebResultOfArrayOfChannelMeg_PnYqa EndGetFeeds(System.IAsyncResult result) {
                object[] _args = new object[0];
                Client_WinPhone.FeedService.WebResultOfArrayOfChannelMeg_PnYqa _result = ((Client_WinPhone.FeedService.WebResultOfArrayOfChannelMeg_PnYqa)(base.EndInvoke("GetFeeds", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAllFeeds(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllFeeds", _args, callback, asyncState);
                return _result;
            }
            
            public Client_WinPhone.FeedService.WebResultOfArrayOfChannelMeg_PnYqa EndGetAllFeeds(System.IAsyncResult result) {
                object[] _args = new object[0];
                Client_WinPhone.FeedService.WebResultOfArrayOfChannelMeg_PnYqa _result = ((Client_WinPhone.FeedService.WebResultOfArrayOfChannelMeg_PnYqa)(base.EndInvoke("GetAllFeeds", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUnfollowFeed(string connectionKey, Client_WinPhone.FeedService.Channel feed, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = connectionKey;
                _args[1] = feed;
                System.IAsyncResult _result = base.BeginInvoke("UnfollowFeed", _args, callback, asyncState);
                return _result;
            }
            
            public Client_WinPhone.FeedService.WebResult EndUnfollowFeed(System.IAsyncResult result) {
                object[] _args = new object[0];
                Client_WinPhone.FeedService.WebResult _result = ((Client_WinPhone.FeedService.WebResult)(base.EndInvoke("UnfollowFeed", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetFeedItems(string connectionKey, Client_WinPhone.FeedService.Channel feed, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = connectionKey;
                _args[1] = feed;
                System.IAsyncResult _result = base.BeginInvoke("GetFeedItems", _args, callback, asyncState);
                return _result;
            }
            
            public Client_WinPhone.FeedService.WebResultOfArrayOfItemMeg_PnYqa EndGetFeedItems(System.IAsyncResult result) {
                object[] _args = new object[0];
                Client_WinPhone.FeedService.WebResultOfArrayOfItemMeg_PnYqa _result = ((Client_WinPhone.FeedService.WebResultOfArrayOfItemMeg_PnYqa)(base.EndInvoke("GetFeedItems", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginReadItem(string connectionKey, Client_WinPhone.FeedService.Item item, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = connectionKey;
                _args[1] = item;
                System.IAsyncResult _result = base.BeginInvoke("ReadItem", _args, callback, asyncState);
                return _result;
            }
            
            public Client_WinPhone.FeedService.WebResult EndReadItem(System.IAsyncResult result) {
                object[] _args = new object[0];
                Client_WinPhone.FeedService.WebResult _result = ((Client_WinPhone.FeedService.WebResult)(base.EndInvoke("ReadItem", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRefreshFeed(Client_WinPhone.FeedService.Channel feed, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = feed;
                System.IAsyncResult _result = base.BeginInvoke("RefreshFeed", _args, callback, asyncState);
                return _result;
            }
            
            public Client_WinPhone.FeedService.WebResult EndRefreshFeed(System.IAsyncResult result) {
                object[] _args = new object[0];
                Client_WinPhone.FeedService.WebResult _result = ((Client_WinPhone.FeedService.WebResult)(base.EndInvoke("RefreshFeed", _args, result)));
                return _result;
            }
        }
    }
}
