//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_WPF.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://asp.net/ApplicationServices/v200", ConfigurationName="ServiceReference.AuthenticationService")]
    public interface AuthenticationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://asp.net/ApplicationServices/v200/AuthenticationService/ValidateUser", ReplyAction="http://asp.net/ApplicationServices/v200/AuthenticationService/ValidateUserRespons" +
            "e")]
        Client_WPF.ServiceReference.ValidateUserResponse ValidateUser(Client_WPF.ServiceReference.ValidateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://asp.net/ApplicationServices/v200/AuthenticationService/Login", ReplyAction="http://asp.net/ApplicationServices/v200/AuthenticationService/LoginResponse")]
        Client_WPF.ServiceReference.LoginResponse Login(Client_WPF.ServiceReference.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://asp.net/ApplicationServices/v200/AuthenticationService/IsLoggedIn", ReplyAction="http://asp.net/ApplicationServices/v200/AuthenticationService/IsLoggedInResponse")]
        Client_WPF.ServiceReference.IsLoggedInResponse IsLoggedIn(Client_WPF.ServiceReference.IsLoggedInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://asp.net/ApplicationServices/v200/AuthenticationService/Logout", ReplyAction="http://asp.net/ApplicationServices/v200/AuthenticationService/LogoutResponse")]
        Client_WPF.ServiceReference.LogoutResponse Logout(Client_WPF.ServiceReference.LogoutRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateUser", WrapperNamespace="http://asp.net/ApplicationServices/v200", IsWrapped=true)]
    public partial class ValidateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asp.net/ApplicationServices/v200", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asp.net/ApplicationServices/v200", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asp.net/ApplicationServices/v200", Order=2)]
        public string customCredential;
        
        public ValidateUserRequest() {
        }
        
        public ValidateUserRequest(string username, string password, string customCredential) {
            this.username = username;
            this.password = password;
            this.customCredential = customCredential;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateUserResponse", WrapperNamespace="http://asp.net/ApplicationServices/v200", IsWrapped=true)]
    public partial class ValidateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asp.net/ApplicationServices/v200", Order=0)]
        public bool ValidateUserResult;
        
        public ValidateUserResponse() {
        }
        
        public ValidateUserResponse(bool ValidateUserResult) {
            this.ValidateUserResult = ValidateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="http://asp.net/ApplicationServices/v200", IsWrapped=true)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asp.net/ApplicationServices/v200", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asp.net/ApplicationServices/v200", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asp.net/ApplicationServices/v200", Order=2)]
        public string customCredential;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asp.net/ApplicationServices/v200", Order=3)]
        public bool isPersistent;
        
        public LoginRequest() {
        }
        
        public LoginRequest(string username, string password, string customCredential, bool isPersistent) {
            this.username = username;
            this.password = password;
            this.customCredential = customCredential;
            this.isPersistent = isPersistent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="http://asp.net/ApplicationServices/v200", IsWrapped=true)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asp.net/ApplicationServices/v200", Order=0)]
        public bool LoginResult;
        
        public LoginResponse() {
        }
        
        public LoginResponse(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsLoggedIn", WrapperNamespace="http://asp.net/ApplicationServices/v200", IsWrapped=true)]
    public partial class IsLoggedInRequest {
        
        public IsLoggedInRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsLoggedInResponse", WrapperNamespace="http://asp.net/ApplicationServices/v200", IsWrapped=true)]
    public partial class IsLoggedInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asp.net/ApplicationServices/v200", Order=0)]
        public bool IsLoggedInResult;
        
        public IsLoggedInResponse() {
        }
        
        public IsLoggedInResponse(bool IsLoggedInResult) {
            this.IsLoggedInResult = IsLoggedInResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Logout", WrapperNamespace="http://asp.net/ApplicationServices/v200", IsWrapped=true)]
    public partial class LogoutRequest {
        
        public LogoutRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogoutResponse", WrapperNamespace="http://asp.net/ApplicationServices/v200", IsWrapped=true)]
    public partial class LogoutResponse {
        
        public LogoutResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthenticationServiceChannel : Client_WPF.ServiceReference.AuthenticationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationServiceClient : System.ServiceModel.ClientBase<Client_WPF.ServiceReference.AuthenticationService>, Client_WPF.ServiceReference.AuthenticationService {
        
        public AuthenticationServiceClient() {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client_WPF.ServiceReference.ValidateUserResponse ValidateUser(Client_WPF.ServiceReference.ValidateUserRequest request) {
            return base.Channel.ValidateUser(request);
        }
        
        public Client_WPF.ServiceReference.LoginResponse Login(Client_WPF.ServiceReference.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public Client_WPF.ServiceReference.IsLoggedInResponse IsLoggedIn(Client_WPF.ServiceReference.IsLoggedInRequest request) {
            return base.Channel.IsLoggedIn(request);
        }
        
        public Client_WPF.ServiceReference.LogoutResponse Logout(Client_WPF.ServiceReference.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
    }
}
