//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace Client_WinPhone.RSSService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebResult", Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client_WinPhone.RSSService.WebResultOfstringAccountDatalrs4Oh3P))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client_WinPhone.RSSService.WebResultOfArrayOfAccountDataYxjpQ34D))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client_WinPhone.RSSService.WebResultOfboolean))]
    public partial class WebResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Client_WinPhone.RSSService.WebResult.ErrorCodeList ErrorCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_WinPhone.RSSService.WebResult.ErrorCodeList ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="WebResult.ErrorCodeList", Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
        public enum ErrorCodeList : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SUCCESS = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            USER_NOT_FOUND = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            USER_ALREADY_EXIST = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            INFORMATION_REQUIRED = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NOT_LOGUED = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            INTERNAL_ERROR = 5,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NEED_PRIVILEGE = 6,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ALREADY_LOGUED = 7,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CANNOT_CREATE_FEED = 8,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CANNOT_GET_FEED = 9,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ITEM_NOT_FOUND = 10,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PARAMETER_ERROR = 11,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            INVALID_PARAMETER = 12,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebResultOfstringAccountDatalrs4Oh3P", Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
    public partial class WebResultOfstringAccountDatalrs4Oh3P : Client_WinPhone.RSSService.WebResult {
        
        private string Value1Field;
        
        private Client_WinPhone.RSSService.AccountData Value2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value1 {
            get {
                return this.Value1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Value1Field, value) != true)) {
                    this.Value1Field = value;
                    this.RaisePropertyChanged("Value1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_WinPhone.RSSService.AccountData Value2 {
            get {
                return this.Value2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Value2Field, value) != true)) {
                    this.Value2Field = value;
                    this.RaisePropertyChanged("Value2");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebResultOfArrayOfAccountDataYxjpQ34D", Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
    public partial class WebResultOfArrayOfAccountDataYxjpQ34D : Client_WinPhone.RSSService.WebResult {
        
        private System.Collections.ObjectModel.ObservableCollection<Client_WinPhone.RSSService.AccountData> ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Client_WinPhone.RSSService.AccountData> Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebResultOfboolean", Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
    public partial class WebResultOfboolean : Client_WinPhone.RSSService.WebResult {
        
        private bool ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountData", Namespace="http://schemas.datacontract.org/2004/07/Server.Services")]
    public partial class AccountData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private bool IsSuperUserField;
        
        private string PasswordField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuperUser {
            get {
                return this.IsSuperUserField;
            }
            set {
                if ((this.IsSuperUserField.Equals(value) != true)) {
                    this.IsSuperUserField = value;
                    this.RaisePropertyChanged("IsSuperUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RSSService.Account")]
    public interface Account {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Account/Register", ReplyAction="http://tempuri.org/Account/RegisterResponse")]
        System.IAsyncResult BeginRegister(string username, string email, string password, System.AsyncCallback callback, object asyncState);
        
        Client_WinPhone.RSSService.WebResult EndRegister(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Account/Login", ReplyAction="http://tempuri.org/Account/LoginResponse")]
        System.IAsyncResult BeginLogin(string username, string password, System.AsyncCallback callback, object asyncState);
        
        Client_WinPhone.RSSService.WebResultOfstringAccountDatalrs4Oh3P EndLogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Account/Logout", ReplyAction="http://tempuri.org/Account/LogoutResponse")]
        System.IAsyncResult BeginLogout(string session_key, System.AsyncCallback callback, object asyncState);
        
        Client_WinPhone.RSSService.WebResult EndLogout(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Account/Update", ReplyAction="http://tempuri.org/Account/UpdateResponse")]
        System.IAsyncResult BeginUpdate(string session_key, Client_WinPhone.RSSService.AccountData updateUser, System.AsyncCallback callback, object asyncState);
        
        Client_WinPhone.RSSService.WebResult EndUpdate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Account/Delete", ReplyAction="http://tempuri.org/Account/DeleteResponse")]
        System.IAsyncResult BeginDelete(string session_key, int id, System.AsyncCallback callback, object asyncState);
        
        Client_WinPhone.RSSService.WebResult EndDelete(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Account/UserList", ReplyAction="http://tempuri.org/Account/UserListResponse")]
        System.IAsyncResult BeginUserList(string session_key, System.AsyncCallback callback, object asyncState);
        
        Client_WinPhone.RSSService.WebResultOfArrayOfAccountDataYxjpQ34D EndUserList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Account/IsConnected", ReplyAction="http://tempuri.org/Account/IsConnectedResponse")]
        System.IAsyncResult BeginIsConnected(string session_key, System.AsyncCallback callback, object asyncState);
        
        Client_WinPhone.RSSService.WebResultOfboolean EndIsConnected(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountChannel : Client_WinPhone.RSSService.Account, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WinPhone.RSSService.WebResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WinPhone.RSSService.WebResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WinPhone.RSSService.WebResultOfstringAccountDatalrs4Oh3P Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WinPhone.RSSService.WebResultOfstringAccountDatalrs4Oh3P)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LogoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WinPhone.RSSService.WebResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WinPhone.RSSService.WebResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WinPhone.RSSService.WebResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WinPhone.RSSService.WebResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WinPhone.RSSService.WebResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WinPhone.RSSService.WebResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UserListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WinPhone.RSSService.WebResultOfArrayOfAccountDataYxjpQ34D Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WinPhone.RSSService.WebResultOfArrayOfAccountDataYxjpQ34D)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsConnectedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public IsConnectedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WinPhone.RSSService.WebResultOfboolean Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WinPhone.RSSService.WebResultOfboolean)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountClient : System.ServiceModel.ClientBase<Client_WinPhone.RSSService.Account>, Client_WinPhone.RSSService.Account {
        
        private BeginOperationDelegate onBeginRegisterDelegate;
        
        private EndOperationDelegate onEndRegisterDelegate;
        
        private System.Threading.SendOrPostCallback onRegisterCompletedDelegate;
        
        private BeginOperationDelegate onBeginLoginDelegate;
        
        private EndOperationDelegate onEndLoginDelegate;
        
        private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginLogoutDelegate;
        
        private EndOperationDelegate onEndLogoutDelegate;
        
        private System.Threading.SendOrPostCallback onLogoutCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateDelegate;
        
        private EndOperationDelegate onEndUpdateDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteDelegate;
        
        private EndOperationDelegate onEndDeleteDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteCompletedDelegate;
        
        private BeginOperationDelegate onBeginUserListDelegate;
        
        private EndOperationDelegate onEndUserListDelegate;
        
        private System.Threading.SendOrPostCallback onUserListCompletedDelegate;
        
        private BeginOperationDelegate onBeginIsConnectedDelegate;
        
        private EndOperationDelegate onEndIsConnectedDelegate;
        
        private System.Threading.SendOrPostCallback onIsConnectedCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public AccountClient() {
        }
        
        public AccountClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<RegisterCompletedEventArgs> RegisterCompleted;
        
        public event System.EventHandler<LoginCompletedEventArgs> LoginCompleted;
        
        public event System.EventHandler<LogoutCompletedEventArgs> LogoutCompleted;
        
        public event System.EventHandler<UpdateCompletedEventArgs> UpdateCompleted;
        
        public event System.EventHandler<DeleteCompletedEventArgs> DeleteCompleted;
        
        public event System.EventHandler<UserListCompletedEventArgs> UserListCompleted;
        
        public event System.EventHandler<IsConnectedCompletedEventArgs> IsConnectedCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Client_WinPhone.RSSService.Account.BeginRegister(string username, string email, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRegister(username, email, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WinPhone.RSSService.WebResult Client_WinPhone.RSSService.Account.EndRegister(System.IAsyncResult result) {
            return base.Channel.EndRegister(result);
        }
        
        private System.IAsyncResult OnBeginRegister(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string email = ((string)(inValues[1]));
            string password = ((string)(inValues[2]));
            return ((Client_WinPhone.RSSService.Account)(this)).BeginRegister(username, email, password, callback, asyncState);
        }
        
        private object[] OnEndRegister(System.IAsyncResult result) {
            Client_WinPhone.RSSService.WebResult retVal = ((Client_WinPhone.RSSService.Account)(this)).EndRegister(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRegisterCompleted(object state) {
            if ((this.RegisterCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RegisterCompleted(this, new RegisterCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RegisterAsync(string username, string email, string password) {
            this.RegisterAsync(username, email, password, null);
        }
        
        public void RegisterAsync(string username, string email, string password, object userState) {
            if ((this.onBeginRegisterDelegate == null)) {
                this.onBeginRegisterDelegate = new BeginOperationDelegate(this.OnBeginRegister);
            }
            if ((this.onEndRegisterDelegate == null)) {
                this.onEndRegisterDelegate = new EndOperationDelegate(this.OnEndRegister);
            }
            if ((this.onRegisterCompletedDelegate == null)) {
                this.onRegisterCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegisterCompleted);
            }
            base.InvokeAsync(this.onBeginRegisterDelegate, new object[] {
                        username,
                        email,
                        password}, this.onEndRegisterDelegate, this.onRegisterCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Client_WinPhone.RSSService.Account.BeginLogin(string username, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogin(username, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WinPhone.RSSService.WebResultOfstringAccountDatalrs4Oh3P Client_WinPhone.RSSService.Account.EndLogin(System.IAsyncResult result) {
            return base.Channel.EndLogin(result);
        }
        
        private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return ((Client_WinPhone.RSSService.Account)(this)).BeginLogin(username, password, callback, asyncState);
        }
        
        private object[] OnEndLogin(System.IAsyncResult result) {
            Client_WinPhone.RSSService.WebResultOfstringAccountDatalrs4Oh3P retVal = ((Client_WinPhone.RSSService.Account)(this)).EndLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginCompleted(object state) {
            if ((this.LoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginCompleted(this, new LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginAsync(string username, string password) {
            this.LoginAsync(username, password, null);
        }
        
        public void LoginAsync(string username, string password, object userState) {
            if ((this.onBeginLoginDelegate == null)) {
                this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
            }
            if ((this.onEndLoginDelegate == null)) {
                this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
            }
            if ((this.onLoginCompletedDelegate == null)) {
                this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
            }
            base.InvokeAsync(this.onBeginLoginDelegate, new object[] {
                        username,
                        password}, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Client_WinPhone.RSSService.Account.BeginLogout(string session_key, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogout(session_key, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WinPhone.RSSService.WebResult Client_WinPhone.RSSService.Account.EndLogout(System.IAsyncResult result) {
            return base.Channel.EndLogout(result);
        }
        
        private System.IAsyncResult OnBeginLogout(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string session_key = ((string)(inValues[0]));
            return ((Client_WinPhone.RSSService.Account)(this)).BeginLogout(session_key, callback, asyncState);
        }
        
        private object[] OnEndLogout(System.IAsyncResult result) {
            Client_WinPhone.RSSService.WebResult retVal = ((Client_WinPhone.RSSService.Account)(this)).EndLogout(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLogoutCompleted(object state) {
            if ((this.LogoutCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LogoutCompleted(this, new LogoutCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LogoutAsync(string session_key) {
            this.LogoutAsync(session_key, null);
        }
        
        public void LogoutAsync(string session_key, object userState) {
            if ((this.onBeginLogoutDelegate == null)) {
                this.onBeginLogoutDelegate = new BeginOperationDelegate(this.OnBeginLogout);
            }
            if ((this.onEndLogoutDelegate == null)) {
                this.onEndLogoutDelegate = new EndOperationDelegate(this.OnEndLogout);
            }
            if ((this.onLogoutCompletedDelegate == null)) {
                this.onLogoutCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLogoutCompleted);
            }
            base.InvokeAsync(this.onBeginLogoutDelegate, new object[] {
                        session_key}, this.onEndLogoutDelegate, this.onLogoutCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Client_WinPhone.RSSService.Account.BeginUpdate(string session_key, Client_WinPhone.RSSService.AccountData updateUser, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdate(session_key, updateUser, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WinPhone.RSSService.WebResult Client_WinPhone.RSSService.Account.EndUpdate(System.IAsyncResult result) {
            return base.Channel.EndUpdate(result);
        }
        
        private System.IAsyncResult OnBeginUpdate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string session_key = ((string)(inValues[0]));
            Client_WinPhone.RSSService.AccountData updateUser = ((Client_WinPhone.RSSService.AccountData)(inValues[1]));
            return ((Client_WinPhone.RSSService.Account)(this)).BeginUpdate(session_key, updateUser, callback, asyncState);
        }
        
        private object[] OnEndUpdate(System.IAsyncResult result) {
            Client_WinPhone.RSSService.WebResult retVal = ((Client_WinPhone.RSSService.Account)(this)).EndUpdate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateCompleted(object state) {
            if ((this.UpdateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateAsync(string session_key, Client_WinPhone.RSSService.AccountData updateUser) {
            this.UpdateAsync(session_key, updateUser, null);
        }
        
        public void UpdateAsync(string session_key, Client_WinPhone.RSSService.AccountData updateUser, object userState) {
            if ((this.onBeginUpdateDelegate == null)) {
                this.onBeginUpdateDelegate = new BeginOperationDelegate(this.OnBeginUpdate);
            }
            if ((this.onEndUpdateDelegate == null)) {
                this.onEndUpdateDelegate = new EndOperationDelegate(this.OnEndUpdate);
            }
            if ((this.onUpdateCompletedDelegate == null)) {
                this.onUpdateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateDelegate, new object[] {
                        session_key,
                        updateUser}, this.onEndUpdateDelegate, this.onUpdateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Client_WinPhone.RSSService.Account.BeginDelete(string session_key, int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDelete(session_key, id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WinPhone.RSSService.WebResult Client_WinPhone.RSSService.Account.EndDelete(System.IAsyncResult result) {
            return base.Channel.EndDelete(result);
        }
        
        private System.IAsyncResult OnBeginDelete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string session_key = ((string)(inValues[0]));
            int id = ((int)(inValues[1]));
            return ((Client_WinPhone.RSSService.Account)(this)).BeginDelete(session_key, id, callback, asyncState);
        }
        
        private object[] OnEndDelete(System.IAsyncResult result) {
            Client_WinPhone.RSSService.WebResult retVal = ((Client_WinPhone.RSSService.Account)(this)).EndDelete(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteCompleted(object state) {
            if ((this.DeleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteAsync(string session_key, int id) {
            this.DeleteAsync(session_key, id, null);
        }
        
        public void DeleteAsync(string session_key, int id, object userState) {
            if ((this.onBeginDeleteDelegate == null)) {
                this.onBeginDeleteDelegate = new BeginOperationDelegate(this.OnBeginDelete);
            }
            if ((this.onEndDeleteDelegate == null)) {
                this.onEndDeleteDelegate = new EndOperationDelegate(this.OnEndDelete);
            }
            if ((this.onDeleteCompletedDelegate == null)) {
                this.onDeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteDelegate, new object[] {
                        session_key,
                        id}, this.onEndDeleteDelegate, this.onDeleteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Client_WinPhone.RSSService.Account.BeginUserList(string session_key, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUserList(session_key, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WinPhone.RSSService.WebResultOfArrayOfAccountDataYxjpQ34D Client_WinPhone.RSSService.Account.EndUserList(System.IAsyncResult result) {
            return base.Channel.EndUserList(result);
        }
        
        private System.IAsyncResult OnBeginUserList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string session_key = ((string)(inValues[0]));
            return ((Client_WinPhone.RSSService.Account)(this)).BeginUserList(session_key, callback, asyncState);
        }
        
        private object[] OnEndUserList(System.IAsyncResult result) {
            Client_WinPhone.RSSService.WebResultOfArrayOfAccountDataYxjpQ34D retVal = ((Client_WinPhone.RSSService.Account)(this)).EndUserList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUserListCompleted(object state) {
            if ((this.UserListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UserListCompleted(this, new UserListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UserListAsync(string session_key) {
            this.UserListAsync(session_key, null);
        }
        
        public void UserListAsync(string session_key, object userState) {
            if ((this.onBeginUserListDelegate == null)) {
                this.onBeginUserListDelegate = new BeginOperationDelegate(this.OnBeginUserList);
            }
            if ((this.onEndUserListDelegate == null)) {
                this.onEndUserListDelegate = new EndOperationDelegate(this.OnEndUserList);
            }
            if ((this.onUserListCompletedDelegate == null)) {
                this.onUserListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUserListCompleted);
            }
            base.InvokeAsync(this.onBeginUserListDelegate, new object[] {
                        session_key}, this.onEndUserListDelegate, this.onUserListCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Client_WinPhone.RSSService.Account.BeginIsConnected(string session_key, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginIsConnected(session_key, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_WinPhone.RSSService.WebResultOfboolean Client_WinPhone.RSSService.Account.EndIsConnected(System.IAsyncResult result) {
            return base.Channel.EndIsConnected(result);
        }
        
        private System.IAsyncResult OnBeginIsConnected(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string session_key = ((string)(inValues[0]));
            return ((Client_WinPhone.RSSService.Account)(this)).BeginIsConnected(session_key, callback, asyncState);
        }
        
        private object[] OnEndIsConnected(System.IAsyncResult result) {
            Client_WinPhone.RSSService.WebResultOfboolean retVal = ((Client_WinPhone.RSSService.Account)(this)).EndIsConnected(result);
            return new object[] {
                    retVal};
        }
        
        private void OnIsConnectedCompleted(object state) {
            if ((this.IsConnectedCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.IsConnectedCompleted(this, new IsConnectedCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void IsConnectedAsync(string session_key) {
            this.IsConnectedAsync(session_key, null);
        }
        
        public void IsConnectedAsync(string session_key, object userState) {
            if ((this.onBeginIsConnectedDelegate == null)) {
                this.onBeginIsConnectedDelegate = new BeginOperationDelegate(this.OnBeginIsConnected);
            }
            if ((this.onEndIsConnectedDelegate == null)) {
                this.onEndIsConnectedDelegate = new EndOperationDelegate(this.OnEndIsConnected);
            }
            if ((this.onIsConnectedCompletedDelegate == null)) {
                this.onIsConnectedCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnIsConnectedCompleted);
            }
            base.InvokeAsync(this.onBeginIsConnectedDelegate, new object[] {
                        session_key}, this.onEndIsConnectedDelegate, this.onIsConnectedCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Client_WinPhone.RSSService.Account CreateChannel() {
            return new AccountClientChannel(this);
        }
        
        private class AccountClientChannel : ChannelBase<Client_WinPhone.RSSService.Account>, Client_WinPhone.RSSService.Account {
            
            public AccountClientChannel(System.ServiceModel.ClientBase<Client_WinPhone.RSSService.Account> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginRegister(string username, string email, string password, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = username;
                _args[1] = email;
                _args[2] = password;
                System.IAsyncResult _result = base.BeginInvoke("Register", _args, callback, asyncState);
                return _result;
            }
            
            public Client_WinPhone.RSSService.WebResult EndRegister(System.IAsyncResult result) {
                object[] _args = new object[0];
                Client_WinPhone.RSSService.WebResult _result = ((Client_WinPhone.RSSService.WebResult)(base.EndInvoke("Register", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginLogin(string username, string password, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = username;
                _args[1] = password;
                System.IAsyncResult _result = base.BeginInvoke("Login", _args, callback, asyncState);
                return _result;
            }
            
            public Client_WinPhone.RSSService.WebResultOfstringAccountDatalrs4Oh3P EndLogin(System.IAsyncResult result) {
                object[] _args = new object[0];
                Client_WinPhone.RSSService.WebResultOfstringAccountDatalrs4Oh3P _result = ((Client_WinPhone.RSSService.WebResultOfstringAccountDatalrs4Oh3P)(base.EndInvoke("Login", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginLogout(string session_key, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = session_key;
                System.IAsyncResult _result = base.BeginInvoke("Logout", _args, callback, asyncState);
                return _result;
            }
            
            public Client_WinPhone.RSSService.WebResult EndLogout(System.IAsyncResult result) {
                object[] _args = new object[0];
                Client_WinPhone.RSSService.WebResult _result = ((Client_WinPhone.RSSService.WebResult)(base.EndInvoke("Logout", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdate(string session_key, Client_WinPhone.RSSService.AccountData updateUser, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = session_key;
                _args[1] = updateUser;
                System.IAsyncResult _result = base.BeginInvoke("Update", _args, callback, asyncState);
                return _result;
            }
            
            public Client_WinPhone.RSSService.WebResult EndUpdate(System.IAsyncResult result) {
                object[] _args = new object[0];
                Client_WinPhone.RSSService.WebResult _result = ((Client_WinPhone.RSSService.WebResult)(base.EndInvoke("Update", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDelete(string session_key, int id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = session_key;
                _args[1] = id;
                System.IAsyncResult _result = base.BeginInvoke("Delete", _args, callback, asyncState);
                return _result;
            }
            
            public Client_WinPhone.RSSService.WebResult EndDelete(System.IAsyncResult result) {
                object[] _args = new object[0];
                Client_WinPhone.RSSService.WebResult _result = ((Client_WinPhone.RSSService.WebResult)(base.EndInvoke("Delete", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUserList(string session_key, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = session_key;
                System.IAsyncResult _result = base.BeginInvoke("UserList", _args, callback, asyncState);
                return _result;
            }
            
            public Client_WinPhone.RSSService.WebResultOfArrayOfAccountDataYxjpQ34D EndUserList(System.IAsyncResult result) {
                object[] _args = new object[0];
                Client_WinPhone.RSSService.WebResultOfArrayOfAccountDataYxjpQ34D _result = ((Client_WinPhone.RSSService.WebResultOfArrayOfAccountDataYxjpQ34D)(base.EndInvoke("UserList", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginIsConnected(string session_key, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = session_key;
                System.IAsyncResult _result = base.BeginInvoke("IsConnected", _args, callback, asyncState);
                return _result;
            }
            
            public Client_WinPhone.RSSService.WebResultOfboolean EndIsConnected(System.IAsyncResult result) {
                object[] _args = new object[0];
                Client_WinPhone.RSSService.WebResultOfboolean _result = ((Client_WinPhone.RSSService.WebResultOfboolean)(base.EndInvoke("IsConnected", _args, result)));
                return _result;
            }
        }
    }
}
