//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.586.
// 
#pragma warning disable 1591

namespace Client_ASP.FeedServ {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_FeedsService", Namespace="http://tempuri.org/")]
    public partial class FeedsService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddNewFeedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFeedsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UnfollowFeedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFeedItemsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FeedsService() {
            this.Url = global::Client_ASP.Properties.Settings.Default.Client_ASP_FeedServ_FeedsService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddNewFeedCompletedEventHandler AddNewFeedCompleted;
        
        /// <remarks/>
        public event GetFeedsCompletedEventHandler GetFeedsCompleted;
        
        /// <remarks/>
        public event UnfollowFeedCompletedEventHandler UnfollowFeedCompleted;
        
        /// <remarks/>
        public event GetFeedItemsCompletedEventHandler GetFeedItemsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FeedsService/AddNewFeed", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WebResultOfRssFeedYxjpQ34D AddNewFeed([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string connectionKey, [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", IsNullable=true)] string uri) {
            object[] results = this.Invoke("AddNewFeed", new object[] {
                        connectionKey,
                        uri});
            return ((WebResultOfRssFeedYxjpQ34D)(results[0]));
        }
        
        /// <remarks/>
        public void AddNewFeedAsync(string connectionKey, string uri) {
            this.AddNewFeedAsync(connectionKey, uri, null);
        }
        
        /// <remarks/>
        public void AddNewFeedAsync(string connectionKey, string uri, object userState) {
            if ((this.AddNewFeedOperationCompleted == null)) {
                this.AddNewFeedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddNewFeedOperationCompleted);
            }
            this.InvokeAsync("AddNewFeed", new object[] {
                        connectionKey,
                        uri}, this.AddNewFeedOperationCompleted, userState);
        }
        
        private void OnAddNewFeedOperationCompleted(object arg) {
            if ((this.AddNewFeedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddNewFeedCompleted(this, new AddNewFeedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FeedsService/GetFeeds", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WebResultOfArrayOfRssFeedYxjpQ34D GetFeeds([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string connectionKey) {
            object[] results = this.Invoke("GetFeeds", new object[] {
                        connectionKey});
            return ((WebResultOfArrayOfRssFeedYxjpQ34D)(results[0]));
        }
        
        /// <remarks/>
        public void GetFeedsAsync(string connectionKey) {
            this.GetFeedsAsync(connectionKey, null);
        }
        
        /// <remarks/>
        public void GetFeedsAsync(string connectionKey, object userState) {
            if ((this.GetFeedsOperationCompleted == null)) {
                this.GetFeedsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFeedsOperationCompleted);
            }
            this.InvokeAsync("GetFeeds", new object[] {
                        connectionKey}, this.GetFeedsOperationCompleted, userState);
        }
        
        private void OnGetFeedsOperationCompleted(object arg) {
            if ((this.GetFeedsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFeedsCompleted(this, new GetFeedsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FeedsService/UnfollowFeed", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WebResult UnfollowFeed([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string connectionKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RssFeed feed) {
            object[] results = this.Invoke("UnfollowFeed", new object[] {
                        connectionKey,
                        feed});
            return ((WebResult)(results[0]));
        }
        
        /// <remarks/>
        public void UnfollowFeedAsync(string connectionKey, RssFeed feed) {
            this.UnfollowFeedAsync(connectionKey, feed, null);
        }
        
        /// <remarks/>
        public void UnfollowFeedAsync(string connectionKey, RssFeed feed, object userState) {
            if ((this.UnfollowFeedOperationCompleted == null)) {
                this.UnfollowFeedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUnfollowFeedOperationCompleted);
            }
            this.InvokeAsync("UnfollowFeed", new object[] {
                        connectionKey,
                        feed}, this.UnfollowFeedOperationCompleted, userState);
        }
        
        private void OnUnfollowFeedOperationCompleted(object arg) {
            if ((this.UnfollowFeedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UnfollowFeedCompleted(this, new UnfollowFeedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FeedsService/GetFeedItems", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WebResultOfArrayOfRssFeedYxjpQ34D GetFeedItems([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string connectionKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RssFeed feed) {
            object[] results = this.Invoke("GetFeedItems", new object[] {
                        connectionKey,
                        feed});
            return ((WebResultOfArrayOfRssFeedYxjpQ34D)(results[0]));
        }
        
        /// <remarks/>
        public void GetFeedItemsAsync(string connectionKey, RssFeed feed) {
            this.GetFeedItemsAsync(connectionKey, feed, null);
        }
        
        /// <remarks/>
        public void GetFeedItemsAsync(string connectionKey, RssFeed feed, object userState) {
            if ((this.GetFeedItemsOperationCompleted == null)) {
                this.GetFeedItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFeedItemsOperationCompleted);
            }
            this.InvokeAsync("GetFeedItems", new object[] {
                        connectionKey,
                        feed}, this.GetFeedItemsOperationCompleted, userState);
        }
        
        private void OnGetFeedItemsOperationCompleted(object arg) {
            if ((this.GetFeedItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFeedItemsCompleted(this, new GetFeedItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
    public partial class WebResultOfRssFeedYxjpQ34D : WebResult {
        
        private RssFeed valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RssFeed Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Services")]
    public partial class RssFeed {
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        private string descriptionField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private int idParentField;
        
        private bool idParentFieldSpecified;
        
        private string linkField;
        
        private string titleField;
        
        private string urlField;
        
        /// <remarks/>
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int IdParent {
            get {
                return this.idParentField;
            }
            set {
                this.idParentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdParentSpecified {
            get {
                return this.idParentFieldSpecified;
            }
            set {
                this.idParentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WebResultOfArrayOfRssFeedYxjpQ34D))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WebResultOfRssFeedYxjpQ34D))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
    public partial class WebResult {
        
        private WebResultErrorCodeList errorCodeField;
        
        private bool errorCodeFieldSpecified;
        
        /// <remarks/>
        public WebResultErrorCodeList ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorCodeSpecified {
            get {
                return this.errorCodeFieldSpecified;
            }
            set {
                this.errorCodeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="WebResult.ErrorCodeList", Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
    public enum WebResultErrorCodeList {
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        USER_NOT_FOUND,
        
        /// <remarks/>
        USER_ALREADY_EXIST,
        
        /// <remarks/>
        INFORMATION_REQUIRED,
        
        /// <remarks/>
        NOT_LOGUED,
        
        /// <remarks/>
        INTERNAL_ERROR,
        
        /// <remarks/>
        NEED_PRIVILEGE,
        
        /// <remarks/>
        ALREADY_LOGUED,
        
        /// <remarks/>
        CANNOT_CREATE_FEED,
        
        /// <remarks/>
        CANNOT_GET_FEED,
        
        /// <remarks/>
        ITEM_NOT_FOUND,
        
        /// <remarks/>
        PARAMETER_ERROR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
    public partial class WebResultOfArrayOfRssFeedYxjpQ34D : WebResult {
        
        private RssFeed[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Services")]
        public RssFeed[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddNewFeedCompletedEventHandler(object sender, AddNewFeedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddNewFeedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddNewFeedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebResultOfRssFeedYxjpQ34D Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebResultOfRssFeedYxjpQ34D)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetFeedsCompletedEventHandler(object sender, GetFeedsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFeedsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFeedsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebResultOfArrayOfRssFeedYxjpQ34D Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebResultOfArrayOfRssFeedYxjpQ34D)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UnfollowFeedCompletedEventHandler(object sender, UnfollowFeedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UnfollowFeedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UnfollowFeedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetFeedItemsCompletedEventHandler(object sender, GetFeedItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFeedItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFeedItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebResultOfArrayOfRssFeedYxjpQ34D Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebResultOfArrayOfRssFeedYxjpQ34D)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591