//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.586.
// 
#pragma warning disable 1591

namespace Client_ASP.FeedServ {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_FeedsService", Namespace="http://tempuri.org/")]
    public partial class FeedsService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddNewFeedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFeedsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllFeedsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UnfollowFeedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFeedItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback RefreshFeedOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FeedsService() {
            this.Url = global::Client_ASP.Properties.Settings.Default.Client_ASP_FeedServ_FeedsService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddNewFeedCompletedEventHandler AddNewFeedCompleted;
        
        /// <remarks/>
        public event GetFeedsCompletedEventHandler GetFeedsCompleted;
        
        /// <remarks/>
        public event GetAllFeedsCompletedEventHandler GetAllFeedsCompleted;
        
        /// <remarks/>
        public event UnfollowFeedCompletedEventHandler UnfollowFeedCompleted;
        
        /// <remarks/>
        public event GetFeedItemsCompletedEventHandler GetFeedItemsCompleted;
        
        /// <remarks/>
        public event ReadItemCompletedEventHandler ReadItemCompleted;
        
        /// <remarks/>
        public event RefreshFeedCompletedEventHandler RefreshFeedCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FeedsService/AddNewFeed", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WebResultOfChannelMeg_PnYqa AddNewFeed([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string connectionKey, [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", IsNullable=true)] string uri) {
            object[] results = this.Invoke("AddNewFeed", new object[] {
                        connectionKey,
                        uri});
            return ((WebResultOfChannelMeg_PnYqa)(results[0]));
        }
        
        /// <remarks/>
        public void AddNewFeedAsync(string connectionKey, string uri) {
            this.AddNewFeedAsync(connectionKey, uri, null);
        }
        
        /// <remarks/>
        public void AddNewFeedAsync(string connectionKey, string uri, object userState) {
            if ((this.AddNewFeedOperationCompleted == null)) {
                this.AddNewFeedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddNewFeedOperationCompleted);
            }
            this.InvokeAsync("AddNewFeed", new object[] {
                        connectionKey,
                        uri}, this.AddNewFeedOperationCompleted, userState);
        }
        
        private void OnAddNewFeedOperationCompleted(object arg) {
            if ((this.AddNewFeedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddNewFeedCompleted(this, new AddNewFeedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FeedsService/GetFeeds", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WebResultOfArrayOfChannelMeg_PnYqa GetFeeds([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string connectionKey) {
            object[] results = this.Invoke("GetFeeds", new object[] {
                        connectionKey});
            return ((WebResultOfArrayOfChannelMeg_PnYqa)(results[0]));
        }
        
        /// <remarks/>
        public void GetFeedsAsync(string connectionKey) {
            this.GetFeedsAsync(connectionKey, null);
        }
        
        /// <remarks/>
        public void GetFeedsAsync(string connectionKey, object userState) {
            if ((this.GetFeedsOperationCompleted == null)) {
                this.GetFeedsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFeedsOperationCompleted);
            }
            this.InvokeAsync("GetFeeds", new object[] {
                        connectionKey}, this.GetFeedsOperationCompleted, userState);
        }
        
        private void OnGetFeedsOperationCompleted(object arg) {
            if ((this.GetFeedsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFeedsCompleted(this, new GetFeedsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FeedsService/GetAllFeeds", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WebResultOfArrayOfChannelMeg_PnYqa GetAllFeeds() {
            object[] results = this.Invoke("GetAllFeeds", new object[0]);
            return ((WebResultOfArrayOfChannelMeg_PnYqa)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllFeedsAsync() {
            this.GetAllFeedsAsync(null);
        }
        
        /// <remarks/>
        public void GetAllFeedsAsync(object userState) {
            if ((this.GetAllFeedsOperationCompleted == null)) {
                this.GetAllFeedsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllFeedsOperationCompleted);
            }
            this.InvokeAsync("GetAllFeeds", new object[0], this.GetAllFeedsOperationCompleted, userState);
        }
        
        private void OnGetAllFeedsOperationCompleted(object arg) {
            if ((this.GetAllFeedsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllFeedsCompleted(this, new GetAllFeedsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FeedsService/UnfollowFeed", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WebResult UnfollowFeed([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string connectionKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Channel feed) {
            object[] results = this.Invoke("UnfollowFeed", new object[] {
                        connectionKey,
                        feed});
            return ((WebResult)(results[0]));
        }
        
        /// <remarks/>
        public void UnfollowFeedAsync(string connectionKey, Channel feed) {
            this.UnfollowFeedAsync(connectionKey, feed, null);
        }
        
        /// <remarks/>
        public void UnfollowFeedAsync(string connectionKey, Channel feed, object userState) {
            if ((this.UnfollowFeedOperationCompleted == null)) {
                this.UnfollowFeedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUnfollowFeedOperationCompleted);
            }
            this.InvokeAsync("UnfollowFeed", new object[] {
                        connectionKey,
                        feed}, this.UnfollowFeedOperationCompleted, userState);
        }
        
        private void OnUnfollowFeedOperationCompleted(object arg) {
            if ((this.UnfollowFeedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UnfollowFeedCompleted(this, new UnfollowFeedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FeedsService/GetFeedItems", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WebResultOfArrayOfItemMeg_PnYqa GetFeedItems([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string connectionKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Channel feed) {
            object[] results = this.Invoke("GetFeedItems", new object[] {
                        connectionKey,
                        feed});
            return ((WebResultOfArrayOfItemMeg_PnYqa)(results[0]));
        }
        
        /// <remarks/>
        public void GetFeedItemsAsync(string connectionKey, Channel feed) {
            this.GetFeedItemsAsync(connectionKey, feed, null);
        }
        
        /// <remarks/>
        public void GetFeedItemsAsync(string connectionKey, Channel feed, object userState) {
            if ((this.GetFeedItemsOperationCompleted == null)) {
                this.GetFeedItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFeedItemsOperationCompleted);
            }
            this.InvokeAsync("GetFeedItems", new object[] {
                        connectionKey,
                        feed}, this.GetFeedItemsOperationCompleted, userState);
        }
        
        private void OnGetFeedItemsOperationCompleted(object arg) {
            if ((this.GetFeedItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFeedItemsCompleted(this, new GetFeedItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FeedsService/ReadItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WebResult ReadItem([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string connectionKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Item item) {
            object[] results = this.Invoke("ReadItem", new object[] {
                        connectionKey,
                        item});
            return ((WebResult)(results[0]));
        }
        
        /// <remarks/>
        public void ReadItemAsync(string connectionKey, Item item) {
            this.ReadItemAsync(connectionKey, item, null);
        }
        
        /// <remarks/>
        public void ReadItemAsync(string connectionKey, Item item, object userState) {
            if ((this.ReadItemOperationCompleted == null)) {
                this.ReadItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadItemOperationCompleted);
            }
            this.InvokeAsync("ReadItem", new object[] {
                        connectionKey,
                        item}, this.ReadItemOperationCompleted, userState);
        }
        
        private void OnReadItemOperationCompleted(object arg) {
            if ((this.ReadItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadItemCompleted(this, new ReadItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FeedsService/RefreshFeed", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WebResult RefreshFeed([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Channel feed) {
            object[] results = this.Invoke("RefreshFeed", new object[] {
                        feed});
            return ((WebResult)(results[0]));
        }
        
        /// <remarks/>
        public void RefreshFeedAsync(Channel feed) {
            this.RefreshFeedAsync(feed, null);
        }
        
        /// <remarks/>
        public void RefreshFeedAsync(Channel feed, object userState) {
            if ((this.RefreshFeedOperationCompleted == null)) {
                this.RefreshFeedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRefreshFeedOperationCompleted);
            }
            this.InvokeAsync("RefreshFeed", new object[] {
                        feed}, this.RefreshFeedOperationCompleted, userState);
        }
        
        private void OnRefreshFeedOperationCompleted(object arg) {
            if ((this.RefreshFeedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RefreshFeedCompleted(this, new RefreshFeedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
    public partial class WebResultOfChannelMeg_PnYqa : WebResult {
        
        private Channel valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Channel Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Data")]
    public partial class Channel {
        
        private string descriptionField;
        
        private string enclosureField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string imageField;
        
        private System.Nullable<System.DateTime> lastBuildDateField;
        
        private bool lastBuildDateFieldSpecified;
        
        private string linkField;
        
        private System.Nullable<System.DateTime> pubDateField;
        
        private bool pubDateFieldSpecified;
        
        private string titleField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Enclosure {
            get {
                return this.enclosureField;
            }
            set {
                this.enclosureField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastBuildDate {
            get {
                return this.lastBuildDateField;
            }
            set {
                this.lastBuildDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastBuildDateSpecified {
            get {
                return this.lastBuildDateFieldSpecified;
            }
            set {
                this.lastBuildDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> PubDate {
            get {
                return this.pubDateField;
            }
            set {
                this.pubDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PubDateSpecified {
            get {
                return this.pubDateFieldSpecified;
            }
            set {
                this.pubDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial class DateTimeOffset {
        
        private System.DateTime dateTimeField;
        
        private short offsetMinutesField;
        
        /// <remarks/>
        public System.DateTime DateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        public short OffsetMinutes {
            get {
                return this.offsetMinutesField;
            }
            set {
                this.offsetMinutesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Data")]
    public partial class Item {
        
        private string authorField;
        
        private string categoryField;
        
        private string commentsField;
        
        private string descriptionField;
        
        private string gUIDField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private int idChannelField;
        
        private bool idChannelFieldSpecified;
        
        private string linkField;
        
        private DateTimeOffset pubDateField;
        
        private bool readField;
        
        private bool readFieldSpecified;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int IdChannel {
            get {
                return this.idChannelField;
            }
            set {
                this.idChannelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdChannelSpecified {
            get {
                return this.idChannelFieldSpecified;
            }
            set {
                this.idChannelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DateTimeOffset PubDate {
            get {
                return this.pubDateField;
            }
            set {
                this.pubDateField = value;
            }
        }
        
        /// <remarks/>
        public bool Read {
            get {
                return this.readField;
            }
            set {
                this.readField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReadSpecified {
            get {
                return this.readFieldSpecified;
            }
            set {
                this.readFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WebResultOfArrayOfItemMeg_PnYqa))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WebResultOfArrayOfChannelMeg_PnYqa))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WebResultOfChannelMeg_PnYqa))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
    public partial class WebResult {
        
        private WebResultErrorCodeList errorCodeField;
        
        private bool errorCodeFieldSpecified;
        
        /// <remarks/>
        public WebResultErrorCodeList ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorCodeSpecified {
            get {
                return this.errorCodeFieldSpecified;
            }
            set {
                this.errorCodeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="WebResult.ErrorCodeList", Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
    public enum WebResultErrorCodeList {
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        USER_NOT_FOUND,
        
        /// <remarks/>
        USER_ALREADY_EXIST,
        
        /// <remarks/>
        INFORMATION_REQUIRED,
        
        /// <remarks/>
        NOT_LOGUED,
        
        /// <remarks/>
        INTERNAL_ERROR,
        
        /// <remarks/>
        NEED_PRIVILEGE,
        
        /// <remarks/>
        ALREADY_LOGUED,
        
        /// <remarks/>
        CANNOT_CREATE_FEED,
        
        /// <remarks/>
        CANNOT_GET_FEED,
        
        /// <remarks/>
        ITEM_NOT_FOUND,
        
        /// <remarks/>
        PARAMETER_ERROR,
        
        /// <remarks/>
        INVALID_PARAMETER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
    public partial class WebResultOfArrayOfItemMeg_PnYqa : WebResult {
        
        private Item[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Data")]
        public Item[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.450")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
    public partial class WebResultOfArrayOfChannelMeg_PnYqa : WebResult {
        
        private Channel[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Data")]
        public Channel[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AddNewFeedCompletedEventHandler(object sender, AddNewFeedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddNewFeedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddNewFeedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebResultOfChannelMeg_PnYqa Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebResultOfChannelMeg_PnYqa)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetFeedsCompletedEventHandler(object sender, GetFeedsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFeedsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFeedsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebResultOfArrayOfChannelMeg_PnYqa Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebResultOfArrayOfChannelMeg_PnYqa)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAllFeedsCompletedEventHandler(object sender, GetAllFeedsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllFeedsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllFeedsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebResultOfArrayOfChannelMeg_PnYqa Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebResultOfArrayOfChannelMeg_PnYqa)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UnfollowFeedCompletedEventHandler(object sender, UnfollowFeedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UnfollowFeedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UnfollowFeedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetFeedItemsCompletedEventHandler(object sender, GetFeedItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFeedItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFeedItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebResultOfArrayOfItemMeg_PnYqa Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebResultOfArrayOfItemMeg_PnYqa)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ReadItemCompletedEventHandler(object sender, ReadItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RefreshFeedCompletedEventHandler(object sender, RefreshFeedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RefreshFeedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RefreshFeedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591