//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_WPF.FeedService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebResult", Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client_WPF.FeedService.WebResultOfArrayOfRssFeedYxjpQ34D))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client_WPF.FeedService.WebResultOfRssFeedYxjpQ34D))]
    public partial class WebResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_WPF.FeedService.WebResult.ErrorCodeList ErrorCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_WPF.FeedService.WebResult.ErrorCodeList ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="WebResult.ErrorCodeList", Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
        public enum ErrorCodeList : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SUCCESS = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            USER_NOT_FOUND = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            USER_ALREADY_EXIST = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            INFORMATION_REQUIRED = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NOT_LOGUED = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            INTERNAL_ERROR = 5,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NEED_PRIVILEGE = 6,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ALREADY_LOGUED = 7,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CANNOT_CREATE_FEED = 8,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CANNOT_GET_FEED = 9,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebResultOfArrayOfRssFeedYxjpQ34D", Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
    [System.SerializableAttribute()]
    public partial class WebResultOfArrayOfRssFeedYxjpQ34D : Client_WPF.FeedService.WebResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_WPF.FeedService.RssFeed[] ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_WPF.FeedService.RssFeed[] Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebResultOfRssFeedYxjpQ34D", Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
    [System.SerializableAttribute()]
    public partial class WebResultOfRssFeedYxjpQ34D : Client_WPF.FeedService.WebResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_WPF.FeedService.RssFeed ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_WPF.FeedService.RssFeed Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RssFeed", Namespace="http://schemas.datacontract.org/2004/07/Server.Services")]
    [System.SerializableAttribute()]
    public partial class RssFeed : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdParentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdParent {
            get {
                return this.IdParentField;
            }
            set {
                if ((this.IdParentField.Equals(value) != true)) {
                    this.IdParentField = value;
                    this.RaisePropertyChanged("IdParent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FeedService.FeedsService")]
    public interface FeedsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FeedsService/AddNewFeed", ReplyAction="http://tempuri.org/FeedsService/AddNewFeedResponse")]
        Client_WPF.FeedService.WebResultOfRssFeedYxjpQ34D AddNewFeed(string connectionKey, System.Uri uri);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/FeedsService/AddNewFeed", ReplyAction="http://tempuri.org/FeedsService/AddNewFeedResponse")]
        System.IAsyncResult BeginAddNewFeed(string connectionKey, System.Uri uri, System.AsyncCallback callback, object asyncState);
        
        Client_WPF.FeedService.WebResultOfRssFeedYxjpQ34D EndAddNewFeed(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FeedsService/GetFeeds", ReplyAction="http://tempuri.org/FeedsService/GetFeedsResponse")]
        Client_WPF.FeedService.WebResultOfArrayOfRssFeedYxjpQ34D GetFeeds(string connectionKey);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/FeedsService/GetFeeds", ReplyAction="http://tempuri.org/FeedsService/GetFeedsResponse")]
        System.IAsyncResult BeginGetFeeds(string connectionKey, System.AsyncCallback callback, object asyncState);
        
        Client_WPF.FeedService.WebResultOfArrayOfRssFeedYxjpQ34D EndGetFeeds(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FeedsServiceChannel : Client_WPF.FeedService.FeedsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddNewFeedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddNewFeedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WPF.FeedService.WebResultOfRssFeedYxjpQ34D Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WPF.FeedService.WebResultOfRssFeedYxjpQ34D)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFeedsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFeedsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WPF.FeedService.WebResultOfArrayOfRssFeedYxjpQ34D Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WPF.FeedService.WebResultOfArrayOfRssFeedYxjpQ34D)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FeedsServiceClient : System.ServiceModel.ClientBase<Client_WPF.FeedService.FeedsService>, Client_WPF.FeedService.FeedsService {
        
        private BeginOperationDelegate onBeginAddNewFeedDelegate;
        
        private EndOperationDelegate onEndAddNewFeedDelegate;
        
        private System.Threading.SendOrPostCallback onAddNewFeedCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetFeedsDelegate;
        
        private EndOperationDelegate onEndGetFeedsDelegate;
        
        private System.Threading.SendOrPostCallback onGetFeedsCompletedDelegate;
        
        public FeedsServiceClient() {
        }
        
        public FeedsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FeedsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeedsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeedsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<AddNewFeedCompletedEventArgs> AddNewFeedCompleted;
        
        public event System.EventHandler<GetFeedsCompletedEventArgs> GetFeedsCompleted;
        
        public Client_WPF.FeedService.WebResultOfRssFeedYxjpQ34D AddNewFeed(string connectionKey, System.Uri uri) {
            return base.Channel.AddNewFeed(connectionKey, uri);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAddNewFeed(string connectionKey, System.Uri uri, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddNewFeed(connectionKey, uri, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Client_WPF.FeedService.WebResultOfRssFeedYxjpQ34D EndAddNewFeed(System.IAsyncResult result) {
            return base.Channel.EndAddNewFeed(result);
        }
        
        private System.IAsyncResult OnBeginAddNewFeed(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string connectionKey = ((string)(inValues[0]));
            System.Uri uri = ((System.Uri)(inValues[1]));
            return this.BeginAddNewFeed(connectionKey, uri, callback, asyncState);
        }
        
        private object[] OnEndAddNewFeed(System.IAsyncResult result) {
            Client_WPF.FeedService.WebResultOfRssFeedYxjpQ34D retVal = this.EndAddNewFeed(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddNewFeedCompleted(object state) {
            if ((this.AddNewFeedCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddNewFeedCompleted(this, new AddNewFeedCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddNewFeedAsync(string connectionKey, System.Uri uri) {
            this.AddNewFeedAsync(connectionKey, uri, null);
        }
        
        public void AddNewFeedAsync(string connectionKey, System.Uri uri, object userState) {
            if ((this.onBeginAddNewFeedDelegate == null)) {
                this.onBeginAddNewFeedDelegate = new BeginOperationDelegate(this.OnBeginAddNewFeed);
            }
            if ((this.onEndAddNewFeedDelegate == null)) {
                this.onEndAddNewFeedDelegate = new EndOperationDelegate(this.OnEndAddNewFeed);
            }
            if ((this.onAddNewFeedCompletedDelegate == null)) {
                this.onAddNewFeedCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddNewFeedCompleted);
            }
            base.InvokeAsync(this.onBeginAddNewFeedDelegate, new object[] {
                        connectionKey,
                        uri}, this.onEndAddNewFeedDelegate, this.onAddNewFeedCompletedDelegate, userState);
        }
        
        public Client_WPF.FeedService.WebResultOfArrayOfRssFeedYxjpQ34D GetFeeds(string connectionKey) {
            return base.Channel.GetFeeds(connectionKey);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetFeeds(string connectionKey, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFeeds(connectionKey, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Client_WPF.FeedService.WebResultOfArrayOfRssFeedYxjpQ34D EndGetFeeds(System.IAsyncResult result) {
            return base.Channel.EndGetFeeds(result);
        }
        
        private System.IAsyncResult OnBeginGetFeeds(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string connectionKey = ((string)(inValues[0]));
            return this.BeginGetFeeds(connectionKey, callback, asyncState);
        }
        
        private object[] OnEndGetFeeds(System.IAsyncResult result) {
            Client_WPF.FeedService.WebResultOfArrayOfRssFeedYxjpQ34D retVal = this.EndGetFeeds(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFeedsCompleted(object state) {
            if ((this.GetFeedsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFeedsCompleted(this, new GetFeedsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFeedsAsync(string connectionKey) {
            this.GetFeedsAsync(connectionKey, null);
        }
        
        public void GetFeedsAsync(string connectionKey, object userState) {
            if ((this.onBeginGetFeedsDelegate == null)) {
                this.onBeginGetFeedsDelegate = new BeginOperationDelegate(this.OnBeginGetFeeds);
            }
            if ((this.onEndGetFeedsDelegate == null)) {
                this.onEndGetFeedsDelegate = new EndOperationDelegate(this.OnEndGetFeeds);
            }
            if ((this.onGetFeedsCompletedDelegate == null)) {
                this.onGetFeedsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFeedsCompleted);
            }
            base.InvokeAsync(this.onBeginGetFeedsDelegate, new object[] {
                        connectionKey}, this.onEndGetFeedsDelegate, this.onGetFeedsCompletedDelegate, userState);
        }
    }
}
