//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_WPF.FeedService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebResult", Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client_WPF.FeedService.WebResultOfArrayOfChannelMeg_PnYqa))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client_WPF.FeedService.WebResultOfArrayOfItemMeg_PnYqa))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Client_WPF.FeedService.WebResultOfChannelMeg_PnYqa))]
    public partial class WebResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_WPF.FeedService.WebResult.ErrorCodeList ErrorCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_WPF.FeedService.WebResult.ErrorCodeList ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="WebResult.ErrorCodeList", Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
        public enum ErrorCodeList : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SUCCESS = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            USER_NOT_FOUND = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            USER_ALREADY_EXIST = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            INFORMATION_REQUIRED = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NOT_LOGUED = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            INTERNAL_ERROR = 5,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NEED_PRIVILEGE = 6,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ALREADY_LOGUED = 7,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CANNOT_CREATE_FEED = 8,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CANNOT_GET_FEED = 9,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            ITEM_NOT_FOUND = 10,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            PARAMETER_ERROR = 11,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            INVALID_PARAMETER = 12,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebResultOfArrayOfChannelMeg_PnYqa", Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
    [System.SerializableAttribute()]
    public partial class WebResultOfArrayOfChannelMeg_PnYqa : Client_WPF.FeedService.WebResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_WPF.FeedService.Channel[] ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_WPF.FeedService.Channel[] Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebResultOfArrayOfItemMeg_PnYqa", Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
    [System.SerializableAttribute()]
    public partial class WebResultOfArrayOfItemMeg_PnYqa : Client_WPF.FeedService.WebResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_WPF.FeedService.Item[] ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_WPF.FeedService.Item[] Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebResultOfChannelMeg_PnYqa", Namespace="http://schemas.datacontract.org/2004/07/Server.Utils")]
    [System.SerializableAttribute()]
    public partial class WebResultOfChannelMeg_PnYqa : Client_WPF.FeedService.WebResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_WPF.FeedService.Channel ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_WPF.FeedService.Channel Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Channel", Namespace="http://schemas.datacontract.org/2004/07/Server.Data")]
    [System.SerializableAttribute()]
    public partial class Channel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnclosureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastBuildDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PubDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Enclosure {
            get {
                return this.EnclosureField;
            }
            set {
                if ((object.ReferenceEquals(this.EnclosureField, value) != true)) {
                    this.EnclosureField = value;
                    this.RaisePropertyChanged("Enclosure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastBuildDate {
            get {
                return this.LastBuildDateField;
            }
            set {
                if ((this.LastBuildDateField.Equals(value) != true)) {
                    this.LastBuildDateField = value;
                    this.RaisePropertyChanged("LastBuildDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PubDate {
            get {
                return this.PubDateField;
            }
            set {
                if ((this.PubDateField.Equals(value) != true)) {
                    this.PubDateField = value;
                    this.RaisePropertyChanged("PubDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/Server.Data")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdChannelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PubDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ReadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GUID {
            get {
                return this.GUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.GUIDField, value) != true)) {
                    this.GUIDField = value;
                    this.RaisePropertyChanged("GUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdChannel {
            get {
                return this.IdChannelField;
            }
            set {
                if ((this.IdChannelField.Equals(value) != true)) {
                    this.IdChannelField = value;
                    this.RaisePropertyChanged("IdChannel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PubDate {
            get {
                return this.PubDateField;
            }
            set {
                if ((this.PubDateField.Equals(value) != true)) {
                    this.PubDateField = value;
                    this.RaisePropertyChanged("PubDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Read {
            get {
                return this.ReadField;
            }
            set {
                if ((this.ReadField.Equals(value) != true)) {
                    this.ReadField = value;
                    this.RaisePropertyChanged("Read");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FeedService.FeedsService")]
    public interface FeedsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FeedsService/AddNewFeed", ReplyAction="http://tempuri.org/FeedsService/AddNewFeedResponse")]
        Client_WPF.FeedService.WebResultOfChannelMeg_PnYqa AddNewFeed(string connectionKey, System.Uri uri);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/FeedsService/AddNewFeed", ReplyAction="http://tempuri.org/FeedsService/AddNewFeedResponse")]
        System.IAsyncResult BeginAddNewFeed(string connectionKey, System.Uri uri, System.AsyncCallback callback, object asyncState);
        
        Client_WPF.FeedService.WebResultOfChannelMeg_PnYqa EndAddNewFeed(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FeedsService/GetFeeds", ReplyAction="http://tempuri.org/FeedsService/GetFeedsResponse")]
        Client_WPF.FeedService.WebResultOfArrayOfChannelMeg_PnYqa GetFeeds(string connectionKey);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/FeedsService/GetFeeds", ReplyAction="http://tempuri.org/FeedsService/GetFeedsResponse")]
        System.IAsyncResult BeginGetFeeds(string connectionKey, System.AsyncCallback callback, object asyncState);
        
        Client_WPF.FeedService.WebResultOfArrayOfChannelMeg_PnYqa EndGetFeeds(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FeedsService/UnfollowFeed", ReplyAction="http://tempuri.org/FeedsService/UnfollowFeedResponse")]
        Client_WPF.FeedService.WebResult UnfollowFeed(string connectionKey, Client_WPF.FeedService.Channel feed);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/FeedsService/UnfollowFeed", ReplyAction="http://tempuri.org/FeedsService/UnfollowFeedResponse")]
        System.IAsyncResult BeginUnfollowFeed(string connectionKey, Client_WPF.FeedService.Channel feed, System.AsyncCallback callback, object asyncState);
        
        Client_WPF.FeedService.WebResult EndUnfollowFeed(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FeedsService/GetFeedItems", ReplyAction="http://tempuri.org/FeedsService/GetFeedItemsResponse")]
        Client_WPF.FeedService.WebResultOfArrayOfItemMeg_PnYqa GetFeedItems(string connectionKey, Client_WPF.FeedService.Channel feed);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/FeedsService/GetFeedItems", ReplyAction="http://tempuri.org/FeedsService/GetFeedItemsResponse")]
        System.IAsyncResult BeginGetFeedItems(string connectionKey, Client_WPF.FeedService.Channel feed, System.AsyncCallback callback, object asyncState);
        
        Client_WPF.FeedService.WebResultOfArrayOfItemMeg_PnYqa EndGetFeedItems(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FeedsService/ReadItem", ReplyAction="http://tempuri.org/FeedsService/ReadItemResponse")]
        Client_WPF.FeedService.WebResult ReadItem(string connectionKey, Client_WPF.FeedService.Item item);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/FeedsService/ReadItem", ReplyAction="http://tempuri.org/FeedsService/ReadItemResponse")]
        System.IAsyncResult BeginReadItem(string connectionKey, Client_WPF.FeedService.Item item, System.AsyncCallback callback, object asyncState);
        
        Client_WPF.FeedService.WebResult EndReadItem(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FeedsServiceChannel : Client_WPF.FeedService.FeedsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddNewFeedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddNewFeedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WPF.FeedService.WebResultOfChannelMeg_PnYqa Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WPF.FeedService.WebResultOfChannelMeg_PnYqa)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFeedsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFeedsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WPF.FeedService.WebResultOfArrayOfChannelMeg_PnYqa Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WPF.FeedService.WebResultOfArrayOfChannelMeg_PnYqa)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UnfollowFeedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UnfollowFeedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WPF.FeedService.WebResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WPF.FeedService.WebResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFeedItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFeedItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WPF.FeedService.WebResultOfArrayOfItemMeg_PnYqa Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WPF.FeedService.WebResultOfArrayOfItemMeg_PnYqa)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReadItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ReadItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Client_WPF.FeedService.WebResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Client_WPF.FeedService.WebResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FeedsServiceClient : System.ServiceModel.ClientBase<Client_WPF.FeedService.FeedsService>, Client_WPF.FeedService.FeedsService {
        
        private BeginOperationDelegate onBeginAddNewFeedDelegate;
        
        private EndOperationDelegate onEndAddNewFeedDelegate;
        
        private System.Threading.SendOrPostCallback onAddNewFeedCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetFeedsDelegate;
        
        private EndOperationDelegate onEndGetFeedsDelegate;
        
        private System.Threading.SendOrPostCallback onGetFeedsCompletedDelegate;
        
        private BeginOperationDelegate onBeginUnfollowFeedDelegate;
        
        private EndOperationDelegate onEndUnfollowFeedDelegate;
        
        private System.Threading.SendOrPostCallback onUnfollowFeedCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetFeedItemsDelegate;
        
        private EndOperationDelegate onEndGetFeedItemsDelegate;
        
        private System.Threading.SendOrPostCallback onGetFeedItemsCompletedDelegate;
        
        private BeginOperationDelegate onBeginReadItemDelegate;
        
        private EndOperationDelegate onEndReadItemDelegate;
        
        private System.Threading.SendOrPostCallback onReadItemCompletedDelegate;
        
        public FeedsServiceClient() {
        }
        
        public FeedsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FeedsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeedsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeedsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<AddNewFeedCompletedEventArgs> AddNewFeedCompleted;
        
        public event System.EventHandler<GetFeedsCompletedEventArgs> GetFeedsCompleted;
        
        public event System.EventHandler<UnfollowFeedCompletedEventArgs> UnfollowFeedCompleted;
        
        public event System.EventHandler<GetFeedItemsCompletedEventArgs> GetFeedItemsCompleted;
        
        public event System.EventHandler<ReadItemCompletedEventArgs> ReadItemCompleted;
        
        public Client_WPF.FeedService.WebResultOfChannelMeg_PnYqa AddNewFeed(string connectionKey, System.Uri uri) {
            return base.Channel.AddNewFeed(connectionKey, uri);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAddNewFeed(string connectionKey, System.Uri uri, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddNewFeed(connectionKey, uri, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Client_WPF.FeedService.WebResultOfChannelMeg_PnYqa EndAddNewFeed(System.IAsyncResult result) {
            return base.Channel.EndAddNewFeed(result);
        }
        
        private System.IAsyncResult OnBeginAddNewFeed(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string connectionKey = ((string)(inValues[0]));
            System.Uri uri = ((System.Uri)(inValues[1]));
            return this.BeginAddNewFeed(connectionKey, uri, callback, asyncState);
        }
        
        private object[] OnEndAddNewFeed(System.IAsyncResult result) {
            Client_WPF.FeedService.WebResultOfChannelMeg_PnYqa retVal = this.EndAddNewFeed(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddNewFeedCompleted(object state) {
            if ((this.AddNewFeedCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddNewFeedCompleted(this, new AddNewFeedCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddNewFeedAsync(string connectionKey, System.Uri uri) {
            this.AddNewFeedAsync(connectionKey, uri, null);
        }
        
        public void AddNewFeedAsync(string connectionKey, System.Uri uri, object userState) {
            if ((this.onBeginAddNewFeedDelegate == null)) {
                this.onBeginAddNewFeedDelegate = new BeginOperationDelegate(this.OnBeginAddNewFeed);
            }
            if ((this.onEndAddNewFeedDelegate == null)) {
                this.onEndAddNewFeedDelegate = new EndOperationDelegate(this.OnEndAddNewFeed);
            }
            if ((this.onAddNewFeedCompletedDelegate == null)) {
                this.onAddNewFeedCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddNewFeedCompleted);
            }
            base.InvokeAsync(this.onBeginAddNewFeedDelegate, new object[] {
                        connectionKey,
                        uri}, this.onEndAddNewFeedDelegate, this.onAddNewFeedCompletedDelegate, userState);
        }
        
        public Client_WPF.FeedService.WebResultOfArrayOfChannelMeg_PnYqa GetFeeds(string connectionKey) {
            return base.Channel.GetFeeds(connectionKey);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetFeeds(string connectionKey, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFeeds(connectionKey, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Client_WPF.FeedService.WebResultOfArrayOfChannelMeg_PnYqa EndGetFeeds(System.IAsyncResult result) {
            return base.Channel.EndGetFeeds(result);
        }
        
        private System.IAsyncResult OnBeginGetFeeds(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string connectionKey = ((string)(inValues[0]));
            return this.BeginGetFeeds(connectionKey, callback, asyncState);
        }
        
        private object[] OnEndGetFeeds(System.IAsyncResult result) {
            Client_WPF.FeedService.WebResultOfArrayOfChannelMeg_PnYqa retVal = this.EndGetFeeds(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFeedsCompleted(object state) {
            if ((this.GetFeedsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFeedsCompleted(this, new GetFeedsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFeedsAsync(string connectionKey) {
            this.GetFeedsAsync(connectionKey, null);
        }
        
        public void GetFeedsAsync(string connectionKey, object userState) {
            if ((this.onBeginGetFeedsDelegate == null)) {
                this.onBeginGetFeedsDelegate = new BeginOperationDelegate(this.OnBeginGetFeeds);
            }
            if ((this.onEndGetFeedsDelegate == null)) {
                this.onEndGetFeedsDelegate = new EndOperationDelegate(this.OnEndGetFeeds);
            }
            if ((this.onGetFeedsCompletedDelegate == null)) {
                this.onGetFeedsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFeedsCompleted);
            }
            base.InvokeAsync(this.onBeginGetFeedsDelegate, new object[] {
                        connectionKey}, this.onEndGetFeedsDelegate, this.onGetFeedsCompletedDelegate, userState);
        }
        
        public Client_WPF.FeedService.WebResult UnfollowFeed(string connectionKey, Client_WPF.FeedService.Channel feed) {
            return base.Channel.UnfollowFeed(connectionKey, feed);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginUnfollowFeed(string connectionKey, Client_WPF.FeedService.Channel feed, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUnfollowFeed(connectionKey, feed, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Client_WPF.FeedService.WebResult EndUnfollowFeed(System.IAsyncResult result) {
            return base.Channel.EndUnfollowFeed(result);
        }
        
        private System.IAsyncResult OnBeginUnfollowFeed(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string connectionKey = ((string)(inValues[0]));
            Client_WPF.FeedService.Channel feed = ((Client_WPF.FeedService.Channel)(inValues[1]));
            return this.BeginUnfollowFeed(connectionKey, feed, callback, asyncState);
        }
        
        private object[] OnEndUnfollowFeed(System.IAsyncResult result) {
            Client_WPF.FeedService.WebResult retVal = this.EndUnfollowFeed(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUnfollowFeedCompleted(object state) {
            if ((this.UnfollowFeedCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UnfollowFeedCompleted(this, new UnfollowFeedCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UnfollowFeedAsync(string connectionKey, Client_WPF.FeedService.Channel feed) {
            this.UnfollowFeedAsync(connectionKey, feed, null);
        }
        
        public void UnfollowFeedAsync(string connectionKey, Client_WPF.FeedService.Channel feed, object userState) {
            if ((this.onBeginUnfollowFeedDelegate == null)) {
                this.onBeginUnfollowFeedDelegate = new BeginOperationDelegate(this.OnBeginUnfollowFeed);
            }
            if ((this.onEndUnfollowFeedDelegate == null)) {
                this.onEndUnfollowFeedDelegate = new EndOperationDelegate(this.OnEndUnfollowFeed);
            }
            if ((this.onUnfollowFeedCompletedDelegate == null)) {
                this.onUnfollowFeedCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUnfollowFeedCompleted);
            }
            base.InvokeAsync(this.onBeginUnfollowFeedDelegate, new object[] {
                        connectionKey,
                        feed}, this.onEndUnfollowFeedDelegate, this.onUnfollowFeedCompletedDelegate, userState);
        }
        
        public Client_WPF.FeedService.WebResultOfArrayOfItemMeg_PnYqa GetFeedItems(string connectionKey, Client_WPF.FeedService.Channel feed) {
            return base.Channel.GetFeedItems(connectionKey, feed);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetFeedItems(string connectionKey, Client_WPF.FeedService.Channel feed, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFeedItems(connectionKey, feed, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Client_WPF.FeedService.WebResultOfArrayOfItemMeg_PnYqa EndGetFeedItems(System.IAsyncResult result) {
            return base.Channel.EndGetFeedItems(result);
        }
        
        private System.IAsyncResult OnBeginGetFeedItems(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string connectionKey = ((string)(inValues[0]));
            Client_WPF.FeedService.Channel feed = ((Client_WPF.FeedService.Channel)(inValues[1]));
            return this.BeginGetFeedItems(connectionKey, feed, callback, asyncState);
        }
        
        private object[] OnEndGetFeedItems(System.IAsyncResult result) {
            Client_WPF.FeedService.WebResultOfArrayOfItemMeg_PnYqa retVal = this.EndGetFeedItems(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFeedItemsCompleted(object state) {
            if ((this.GetFeedItemsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFeedItemsCompleted(this, new GetFeedItemsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFeedItemsAsync(string connectionKey, Client_WPF.FeedService.Channel feed) {
            this.GetFeedItemsAsync(connectionKey, feed, null);
        }
        
        public void GetFeedItemsAsync(string connectionKey, Client_WPF.FeedService.Channel feed, object userState) {
            if ((this.onBeginGetFeedItemsDelegate == null)) {
                this.onBeginGetFeedItemsDelegate = new BeginOperationDelegate(this.OnBeginGetFeedItems);
            }
            if ((this.onEndGetFeedItemsDelegate == null)) {
                this.onEndGetFeedItemsDelegate = new EndOperationDelegate(this.OnEndGetFeedItems);
            }
            if ((this.onGetFeedItemsCompletedDelegate == null)) {
                this.onGetFeedItemsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFeedItemsCompleted);
            }
            base.InvokeAsync(this.onBeginGetFeedItemsDelegate, new object[] {
                        connectionKey,
                        feed}, this.onEndGetFeedItemsDelegate, this.onGetFeedItemsCompletedDelegate, userState);
        }
        
        public Client_WPF.FeedService.WebResult ReadItem(string connectionKey, Client_WPF.FeedService.Item item) {
            return base.Channel.ReadItem(connectionKey, item);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginReadItem(string connectionKey, Client_WPF.FeedService.Item item, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReadItem(connectionKey, item, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Client_WPF.FeedService.WebResult EndReadItem(System.IAsyncResult result) {
            return base.Channel.EndReadItem(result);
        }
        
        private System.IAsyncResult OnBeginReadItem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string connectionKey = ((string)(inValues[0]));
            Client_WPF.FeedService.Item item = ((Client_WPF.FeedService.Item)(inValues[1]));
            return this.BeginReadItem(connectionKey, item, callback, asyncState);
        }
        
        private object[] OnEndReadItem(System.IAsyncResult result) {
            Client_WPF.FeedService.WebResult retVal = this.EndReadItem(result);
            return new object[] {
                    retVal};
        }
        
        private void OnReadItemCompleted(object state) {
            if ((this.ReadItemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReadItemCompleted(this, new ReadItemCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReadItemAsync(string connectionKey, Client_WPF.FeedService.Item item) {
            this.ReadItemAsync(connectionKey, item, null);
        }
        
        public void ReadItemAsync(string connectionKey, Client_WPF.FeedService.Item item, object userState) {
            if ((this.onBeginReadItemDelegate == null)) {
                this.onBeginReadItemDelegate = new BeginOperationDelegate(this.OnBeginReadItem);
            }
            if ((this.onEndReadItemDelegate == null)) {
                this.onEndReadItemDelegate = new EndOperationDelegate(this.OnEndReadItem);
            }
            if ((this.onReadItemCompletedDelegate == null)) {
                this.onReadItemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReadItemCompleted);
            }
            base.InvokeAsync(this.onBeginReadItemDelegate, new object[] {
                        connectionKey,
                        item}, this.onEndReadItemDelegate, this.onReadItemCompletedDelegate, userState);
        }
    }
}
